<x-capstone::card x-show="showForm && (editing ? canEdit(editing) : canCreate)"><form @submit.prevent="save()" class="space-y-6"><div class="px-6 space-y-2"><h2 class="font-semibold leading-none" x-text="formTitle"></h2><p class="text-sm text-muted-foreground" x-text="editing ? 'Edit your proposal and submit for review.' : 'Fill in the details for your proposed title and select a supervisor.'"></p></div><div class="px-6 grid gap-4">
<x-capstone::alert title="Error" variant="destructive" x-show="errors.root"><span x-text="errors.root"></span></x-capstone::alert>
<label class="grid gap-2 text-sm font-medium" for="proposal-title">Title<x-capstone::input id="proposal-title" x-model="form.title" required minlength="5" maxlength="100" placeholder="Enter your proposed title" /><span class="text-destructive" x-text="errors.title?.[0]"></span></label>
@foreach(['description'=>['Description','Describe your project in detail','Provide a clear description of what your project will accomplish.'],'problem_statement'=>['Problem Statement','What problem does your project solve?','Describe the specific problem or gap that your project addresses.'],'scope'=>['Scope','Define the boundaries and scope of your project','Define what is included and excluded in your project scope.']] as $key=>$field)
<label class="grid gap-2 text-sm font-medium" for="proposal-{{ $key }}">{{ $field[0] }}<textarea id="proposal-{{ $key }}" x-model="form.{{ $key }}" required minlength="{{ $key==='description'?20:10 }}" maxlength="{{ $key==='description'?500:300 }}" rows="3" placeholder="{{ $field[1] }}" class="border-input placeholder:text-muted-foreground w-full rounded-md border bg-transparent px-3 py-2 text-sm shadow-xs"></textarea><span class="text-muted-foreground font-normal">{{ $field[2] }}</span><span class="text-destructive" x-text="errors.{{ $key }}?.[0]"></span></label>
@endforeach
<fieldset class="space-y-3"><legend class="text-sm font-medium">Specializations</legend><p class="text-sm text-muted-foreground">Select all specializations that apply to your project.</p><div class="grid gap-3"><template x-for="spec in specs" :key="spec"><label class="flex items-center gap-3 text-sm"><input type="checkbox" :value="spec" x-model="form.specializations" class="size-4 rounded border-input accent-primary"><span x-text="spec"></span></label></template></div><p class="text-sm text-destructive" x-text="errors.specializations?.[0]"></p></fieldset>
<label class="grid gap-2 text-sm font-medium" for="proposal-supervisor">Supervisor (Dosen Pembimbing)<span class="text-muted-foreground font-normal">Select a lecturer who will supervise your project.</span><select id="proposal-supervisor" x-model="form.proposed_supervisor_id" required class="border-input h-9 w-full rounded-md border bg-transparent px-3 text-sm shadow-xs"><option value="">Select a supervisor</option><template x-for="lecturer in lecturers" :key="lecturer.id"><option :value="String(lecturer.id)" x-text="person(lecturer)+' ('+email(lecturer)+')'"></option></template></select><span class="text-destructive" x-text="errors.proposed_supervisor_id?.[0]"></span></label>
</div><div class="px-6 flex justify-end gap-2"><x-capstone::button variant="outline" @click="showForm=false; editing=null" ::disabled="saving">Cancel</x-capstone::button><x-capstone::button type="submit" ::disabled="saving"><x-capstone::icon name="Send" /><span x-text="editing ? (editing.supervisor_approval_status==='PENDING'?'Update Proposal':'Resubmit Proposal') : 'Submit Proposal'"></span></x-capstone::button></div></form></x-capstone::card>
