@extends('capstone::layouts.app')
@section('title','Title Details')
@section('content')
<div x-data="studentTitleDetail" class="space-y-6">@include('capstone::partials.loading')
<template x-if="!loading && !error && title"><div class="space-y-6"><div class="flex flex-wrap items-center gap-4"><x-capstone::button href="/mahasiswa/titles" variant="ghost" size="icon" aria-label="Back to Titles"><x-capstone::icon name="ArrowLeft" class="h-5 w-5" /></x-capstone::button><div class="flex-1"><h1 class="text-3xl font-bold tracking-tight" x-text="title.title"></h1><p class="text-muted-foreground">By <span x-text="person(title.lecturer)"></span></p></div><x-capstone::button @click="bid()" ::disabled="!canBid || saving"><x-capstone::icon name="Lock" x-show="!canBid" class="h-3 w-3" />Bid for This Title</x-capstone::button></div><x-capstone::alert title="Belum Bisa Bidding Judul Dosen" variant="destructive" icon="Lock" x-show="!canBid && group?.is_solo && members.length < minMembers">Kelompok solo Anda memiliki <span x-text="members.length"></span> dari minimal <span x-text="minMembers"></span> anggota. Untuk membuka bidding judul dosen, tambah anggota di <x-capstone::feature-link href="/mahasiswa/group" class="underline font-bold">Grup Saya</x-capstone::feature-link> hingga mencapai minimal. Sementara itu, Anda tetap dapat <x-capstone::feature-link href="/mahasiswa/propose-title" class="underline font-medium">mengajukan judul sendiri</x-capstone::feature-link>.</x-capstone::alert><x-capstone::alert title="Belum Bisa Bidding" icon="Lock" x-show="!canBid && !(group?.is_solo && members.length < minMembers) && bidBlockers.length"><ul class="list-disc pl-5 space-y-1"><template x-for="(reason, i) in bidBlockers" :key="i"><li x-text="reason"></li></template></ul></x-capstone::alert><div class="grid gap-6 md:grid-cols-2">
@foreach(['description'=>'Description','problem_statement'=>'Problem Statement','scope'=>'Scope'] as $key=>$label)<x-capstone::card :title="$label"><div class="px-6"><p class="text-sm whitespace-pre-wrap" x-text="title.{{ $key }} || 'Not specified'"></p></div></x-capstone::card>@endforeach
<x-capstone::card title="Details"><div class="px-6 space-y-3"><div class="text-sm"><span class="text-muted-foreground">Lecturer:</span><span class="ml-2 font-medium" x-text="person(title.lecturer)"></span></div><div class="text-sm"><span class="text-muted-foreground">Available Slots:</span><span class="ml-2 font-medium" x-text="slots+'/'+title.quota+' groups'"></span></div><div><span class="text-sm text-muted-foreground">Specializations:</span><div class="flex flex-wrap gap-1 mt-1"><template x-for="spec in title.specializations || []" :key="spec"><x-capstone::badge variant="outline" x-text="spec" /></template><span x-show="!title.specializations?.length" class="text-sm text-muted-foreground">None specified</span></div></div></div></x-capstone::card></div></div></template>
<div x-show="!loading && !title" class="text-center py-12"><p class="text-muted-foreground">Title not found.</p><x-capstone::button href="/mahasiswa/titles" variant="outline" class="mt-4">Back to Titles</x-capstone::button></div></div>
@endsection
