@extends('capstone::layouts.app')
@section('title','Peer Review')
@section('content')
<div x-data="capstonePeerReview" class="space-y-6">
    <div class="flex items-start justify-between gap-4"><div><h1 class="text-3xl font-extrabold tracking-tight">Peer Review</h1><p class="text-muted-foreground"><span x-text="indicators.length ? 'Rate each group member on '+indicators.length+' indicator'+(indicators.length!==1?'s':'') : 'Peer review configuration pending.'"></span><x-capstone::badge variant="secondary" class="ml-2 border-green-300 text-green-700 bg-green-50" x-show="hasSubmitted"><x-capstone::icon name="CircleCheck" class="h-3 w-3" />Submitted</x-capstone::badge></p></div><x-capstone::badge variant="secondary" class="px-3 py-1 text-sm">Mahasiswa</x-capstone::badge></div>
    @include('capstone::partials.loading')
    <div x-show="!loading && !error" x-cloak>
        <div x-show="isLocked" class="text-center py-16 border rounded-lg border-dashed text-muted-foreground bg-white"><x-capstone::icon name="Lock" class="h-12 w-12 mx-auto mb-4 opacity-50" /><h2 class="text-xl font-bold mb-2">Peer Review Locked</h2><p>Peer review is available after your group registers for Expo.</p></div>
        <div x-show="!isLocked && !indicators.length" class="text-center py-16 border rounded-lg border-dashed text-muted-foreground bg-muted/20"><x-capstone::icon name="Star" class="h-12 w-12 mx-auto mb-4 opacity-30" /><h2 class="text-lg text-foreground font-semibold mb-2">Not Yet Available</h2><p>No peer review indicators have been set up for this period.<br>Please wait for your admin to configure them.</p></div>
        <div x-show="!isLocked && indicators.length && !reviewable.length" class="text-center py-16 border rounded-lg border-dashed text-muted-foreground">No other group members to review.</div>
        <div x-show="!isLocked && indicators.length && reviewable.length" class="grid grid-cols-1 lg:grid-cols-12 gap-8">
            <div class="lg:col-span-4 space-y-6">
                <x-capstone::card class="border-primary/20 shadow-lg overflow-hidden"><div class="h-2 bg-primary"></div><div class="px-6"><h2 class="font-semibold flex items-center gap-2"><x-capstone::icon name="Users" class="h-5 w-5 text-primary" />Group Information</h2></div><div class="px-6 space-y-4"><div class="p-4 bg-muted/30 rounded-xl space-y-3">
                    <div x-show="group?.title" class="space-y-1"><p class="text-xs text-muted-foreground uppercase font-semibold">Project Title</p><p class="font-medium text-sm leading-tight text-primary" x-text="group?.title?.title || group?.title?.name"></p></div><hr class="border-primary/10"><div class="space-y-1"><p class="text-xs text-muted-foreground uppercase font-semibold">Group Code</p><p class="font-medium" x-text="group?.code || 'Group '+group?.id"></p></div><hr class="border-primary/10"><div class="space-y-2"><p class="text-xs text-muted-foreground uppercase font-semibold">Members</p><template x-for="member in members" :key="member.student.id"><div class="flex items-center gap-3 bg-background p-2 rounded-lg border border-primary/5 shadow-sm"><span class="h-8 w-8 shrink-0 rounded-full bg-primary/10 flex items-center justify-center text-primary font-bold text-xs" x-text="member.student.name.charAt(0)"></span><div class="min-w-0"><p class="text-sm font-semibold truncate" x-text="member.student.name+(member.student.id===currentUser?' (You)':'')"></p><p class="text-xs text-muted-foreground" x-text="member.student.nim || member.student.student_number || member.student.email"></p></div><x-capstone::badge variant="secondary" x-show="member.is_leader" class="ml-auto text-xs shrink-0">Leader</x-capstone::badge></div></template></div>
                </div></div></x-capstone::card>
                <x-capstone::card class="border-primary/10 shadow-md"><div class="px-6"><h2 class="text-lg font-semibold flex items-center gap-2"><x-capstone::icon name="Info" class="h-4 w-4 text-primary" />Scoring Guide</h2><p class="text-sm text-muted-foreground">How to evaluate your peers</p></div><div class="px-6 space-y-4"><div class="text-sm text-muted-foreground space-y-2"><p class="font-medium text-foreground">Scale: 1 (Worst) – 4 (Best)</p><div class="grid grid-cols-2 gap-2 text-xs pl-2"><span class="text-red-600">1 = Poor</span><span class="text-orange-600">2 = Fair</span><span class="text-primary">3 = Good</span><span class="text-success">4 = Excellent</span></div><hr><p>• Each indicator has a specific weight</p><p>• Weighted average is calculated automatically</p><p>• Scores are converted to 0–100 scale for reports</p><p>• Comments are optional but encouraged</p></div><div x-show="hasSubmitted" class="flex items-start gap-2 text-sm text-green-700 bg-green-50 p-3 rounded-lg"><x-capstone::icon name="CircleCheck" class="h-4 w-4 shrink-0 mt-0.5" /><p>Your reviews have been <strong>submitted</strong>. You can view your scores but cannot make changes.</p></div></div></x-capstone::card>
            </div>
            <div class="lg:col-span-8 space-y-6 min-w-0">
                <x-capstone::card class="shadow-xl"><div class="px-6 bg-muted/30 flex items-center justify-between"><div><h2 class="font-semibold" x-text="hasSubmitted ? 'Submitted Peer Review' : 'Assessment Rubric'"></h2><p class="text-sm text-muted-foreground" x-text="hasSubmitted ? 'Your submitted scores (read-only)' : 'Enter scores (1-4) for each member and indicator'"></p></div><x-capstone::badge variant="secondary" class="text-sm px-3 py-1" x-show="hasSubmitted"><x-capstone::icon name="Lock" class="h-3 w-3" />Locked</x-capstone::badge></div>
                    <div x-show="hasSubmitted" class="p-6">@include('capstone::partials.peer-review-summary')</div>
                    <div x-show="!hasSubmitted" class="divide-y divide-border"><template x-for="ind in indicators" :key="ind.id"><div class="p-6 space-y-4 hover:bg-muted/5 transition-colors"><div class="flex items-start justify-between gap-4"><div class="space-y-1"><div class="flex items-center gap-2"><span x-show="ind.code" class="text-xs font-bold px-2 py-0.5 bg-primary/10 text-primary rounded" x-text="ind.code"></span><h3 class="font-bold text-lg" x-text="ind.name"></h3></div><p class="text-sm text-muted-foreground" x-text="ind.description"></p></div><div class="shrink-0 text-right"><p class="text-xs font-bold text-muted-foreground uppercase">Weight</p><p class="text-lg font-extrabold text-primary" x-text="ind.weight+'%'"></p></div></div>
                        <div class="grid grid-cols-1 gap-4 mt-4"><template x-for="member in reviewable" :key="member.student.id"><fieldset :disabled="hasSubmitted || isLocked || saving" class="space-y-2 p-3 rounded-lg bg-muted/20 border border-border/50"><div class="flex flex-wrap items-center justify-between gap-2"><span class="text-xs flex items-center gap-2 flex-1"><span class="h-6 w-6 shrink-0 rounded-full bg-primary/10 flex items-center justify-center text-primary font-bold text-[10px]" x-text="member.student.name.charAt(0)"></span><span x-text="member.student.name"></span><x-capstone::badge variant="outline" class="text-[10px] px-1 py-0" x-show="member.is_leader">Leader</x-capstone::badge></span><label class="flex items-center gap-2 text-xs text-muted-foreground">Score:<select x-model.number="scores[member.student.id][ind.id].score" class="w-20 h-8 rounded-md border text-center text-sm bg-background" :aria-label="member.student.name+' — '+ind.name"><option value="0">-</option><option>1</option><option>2</option><option>3</option><option>4</option></select></label></div><textarea x-model="scores[member.student.id][ind.id].comment" placeholder="Feedback (optional)..." rows="1" maxlength="5000" class="w-full h-10 min-h-[40px] rounded-md border px-3 text-sm py-2 bg-transparent" :aria-label="'Feedback for '+member.student.name+' — '+ind.name"></textarea></fieldset></template></div>
                    </div></template></div>
                </x-capstone::card>
                <x-capstone::card class="border-primary shadow-lg bg-primary/5"><div class="p-6 flex flex-col md:flex-row items-center justify-between gap-6"><div class="space-y-2"><h4 class="font-bold text-muted-foreground">Score Summary</h4><div class="flex gap-4 flex-wrap"><template x-for="member in reviewable" :key="member.student.id"><div class="text-center"><p class="text-xs text-muted-foreground" x-text="member.student.name.split(' ')[0]"></p><p class="text-2xl font-black text-primary" x-text="average(member.student.id)"></p></div></template></div></div><x-capstone::button size="lg" class="px-8 font-bold shadow-xl shadow-primary/20 hover:scale-105 transition-transform" x-show="!hasSubmitted" ::disabled="saving || !canSubmit" @click="confirm">Submit Reviews<x-capstone::icon name="Send" class="ml-2 h-5 w-5" /></x-capstone::button><div x-show="hasSubmitted" class="flex items-center gap-2 text-green-700 bg-green-50 px-4 py-2 rounded-lg"><x-capstone::icon name="CircleCheck" class="h-5 w-5" /><span class="font-semibold">Submitted</span></div></div></x-capstone::card>
            </div>
        </div>
    </div>
    <x-capstone::dialog id="peer-confirm" title="Confirm Peer Review Submission" description="Please review your scores carefully. Once submitted, you cannot make changes." class="max-w-2xl">
        <div class="space-y-6 py-4">@include('capstone::partials.peer-review-summary')<div class="bg-primary/5 p-4 rounded-lg text-center"><p class="text-sm text-muted-foreground">Overall Average Score (0–100 scale)</p><p class="text-3xl font-black text-primary" x-text="overall"></p></div><div class="flex items-start gap-3 p-4 bg-red-50 border border-red-200 rounded-lg text-red-800"><x-capstone::icon name="AlertTriangle" class="h-5 w-5 shrink-0 mt-0.5" /><div class="text-sm"><p class="font-semibold">This action cannot be undone</p><p class="text-red-700">Once you submit your peer reviews, you will not be able to edit them. Please verify all scores are correct before confirming.</p></div></div></div><div class="flex justify-end gap-2"><x-capstone::button variant="outline" @click="$el.closest('dialog').close()">Cancel</x-capstone::button><x-capstone::button @click="submit" ::disabled="saving || !canSubmit"><x-capstone::icon name="Send" />Confirm Submission</x-capstone::button></div>
    </x-capstone::dialog>
    <x-capstone::card x-show="status?.has_completed_peer_review" class="border-green-200 bg-green-50 shadow-lg"><div class="p-6 flex flex-wrap items-center justify-between gap-4"><div class="flex items-center gap-4"><div class="h-12 w-12 rounded-full bg-green-100 flex items-center justify-center"><x-capstone::icon name="CircleCheck" class="h-6 w-6 text-green-600" /></div><div><h4 class="font-bold text-green-800">Peer Review Completed!</h4><p class="text-sm text-green-700">TA Status: <strong x-text="status?.ta_status==='TA_ACTIVE' ? 'Active' : status?.ta_status==='TA_DONE' ? 'Completed' : 'Blocked'"></strong> — <span x-text="status?.can_access_ta ? 'You can now access the TA phase.' : 'TA access will be granted shortly.'"></span></p></div></div><x-capstone::button href="/mahasiswa/ta-submission" variant="outline" x-show="status?.can_access_ta" class="border-green-600 text-green-700 hover:bg-green-100 font-bold">Go to TA Phase<x-capstone::icon name="ArrowRight" /></x-capstone::button></div></x-capstone::card>
</div>
@endsection
