@extends('capstone::layouts.app')
@section('title','Phase Requirements')
@section('content')
@php
    $phase = strtoupper($pageParams['phase'] ?? '');
    abort_unless(in_array($phase, ['PDC1','SEMPRO','PDC2','EXPO','TA','SIDANG'], true), 404);
@endphp
<div class="space-y-6" x-data="documentRequirements(@js($phase))">
    <div class="flex items-center justify-between"><a :href="phaseUrl()" class="inline-flex h-8 items-center gap-2 rounded-md border border-grey-100 px-3 text-sm font-medium text-grey-600 hover:bg-grey-25"><x-capstone::icon name="ChevronLeft" class="h-4 w-4" />Kembali</a><x-capstone::button size="sm" @click="save()" ::disabled="!editable"><x-capstone::icon name="Loader2" x-show="saving" class="mr-2 h-4 w-4 animate-spin" /><x-capstone::icon name="Save" class="mr-2 h-4 w-4" />Simpan</x-capstone::button></div>
    @include('capstone::pages.admin.document-requirements.finalized')
    <div class="grid grid-cols-1 gap-6 lg:grid-cols-[300px_1fr]">
        <div class="space-y-6"><x-capstone::card><div class="px-6"><h2 class="text-lg font-semibold">Informasi Fase</h2></div><div class="space-y-4 px-6"><div><p class="text-sm font-medium text-muted-foreground">Nama Fase</p><div class="mt-1"><x-capstone::badge variant="outline" class="px-3 py-1 text-base" x-text="labels[phase]" /></div></div><div><p class="text-sm font-medium text-muted-foreground">Deskripsi</p><p class="mt-1 text-sm text-muted-foreground" x-text="descriptions[phase]"></p></div><div><label for="phase-period" class="text-sm font-medium text-muted-foreground">Periode</label><select id="phase-period" x-model="selectedPeriod" @change="load()" :disabled="saving" class="mt-1 h-9 w-full rounded-md border px-3 text-sm"><option value="" disabled>Select period</option><template x-for="period in periods" :key="period.id"><option :value="String(period.id)" x-text="period.name+(period.is_active ? ' (Active)' : '')"></option></template></select></div><div class="border-t pt-2"><div class="flex items-center justify-between"><span class="text-sm text-muted-foreground">Total Dokumen</span><span class="text-lg font-semibold" x-text="items.length"></span></div><div class="mt-1 flex items-center justify-between"><span class="text-sm text-muted-foreground">Required</span><span class="text-lg font-semibold text-emerald-600" x-text="requiredCount"></span></div></div></div></x-capstone::card></div>
        <div class="min-w-0"><x-capstone::card><div class="flex items-center justify-between px-6"><h2 class="text-lg font-semibold">Tipe Dokumen</h2><x-capstone::button variant="outline" size="sm" @click="add()" ::disabled="!editable || !newName.trim()"><x-capstone::icon name="Plus" class="mr-2 h-4 w-4" />Tambah</x-capstone::button></div><div class="space-y-4 px-6">
            <form x-show="!finalized" @submit.prevent="add()" class="flex items-start gap-2"><div class="flex-1 space-y-2"><x-capstone::input x-model="newName" placeholder="Nama dokumen" aria-label="Nama dokumen baru" maxlength="255" ::disabled="!editable" /><x-capstone::input x-model="newDescription" placeholder="Deskripsi (opsional)" aria-label="Deskripsi dokumen baru" ::disabled="!editable" /></div><x-capstone::button type="submit" size="icon" ::disabled="!editable || !newName.trim()" aria-label="Tambah dokumen"><x-capstone::icon name="Plus" class="h-4 w-4" /></x-capstone::button></form>
            <div class="rounded-lg border border-dashed">@include('capstone::partials.loading')<div x-show="!loading && !error && !items.length" x-cloak class="flex flex-col items-center px-4 py-16 text-center"><x-capstone::icon name="FileText" class="mb-4 h-8 w-8 text-muted-foreground" /><p class="font-medium text-muted-foreground">Belum ada dokumen yang dikonfigurasi</p><p class="mt-1 text-sm text-muted-foreground">Tambahkan dokumen menggunakan form di atas</p></div><div x-show="!loading && !error && items.length" x-cloak class="overflow-x-auto"><table class="w-full text-sm"><thead><tr class="border-b bg-gray-50/50"><th class="w-10 p-2"><span class="sr-only">Required</span></th><th class="h-10 p-2 text-left font-semibold text-gray-700">Nama Dokumen</th><th class="p-2 text-left font-semibold text-gray-700">Deskripsi</th><th class="w-20 p-2 text-center font-semibold text-gray-700">Aksi</th></tr></thead><tbody><template x-for="item in items" :key="item._key"><tr class="border-b last:border-0 hover:bg-muted/50"><td class="p-2"><input type="checkbox" x-model="item.is_required" :disabled="!editable" :aria-label="'Required: '+item.name" class="h-4 w-4 rounded border accent-primary" /></td><td class="p-2"><span x-show="finalized" class="font-medium" x-text="item.name"></span><x-capstone::input x-show="!finalized" x-model="item.name" class="h-8 min-w-32 text-sm" maxlength="255" aria-label="Nama Dokumen" ::disabled="!editable" /></td><td class="p-2"><span x-show="finalized" class="text-muted-foreground" x-text="item.description || '-'"></span><x-capstone::input x-show="!finalized" x-model="item.description" placeholder="Deskripsi" class="h-8 min-w-32 text-sm" aria-label="Deskripsi" ::disabled="!editable" /></td><td class="p-2 text-center"><x-capstone::button variant="ghost" size="icon-sm" class="text-destructive hover:text-destructive" @click="remove(item)" ::disabled="!editable" aria-label="Hapus dokumen"><x-capstone::icon name="Trash2" class="h-4 w-4" /></x-capstone::button></td></tr></template></tbody></table></div></div>
        </div></x-capstone::card></div>
    </div>
</div>
@endsection
