<?php

namespace Modules\BankSoal\Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BsMataKuliahCplSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('bs_mata_kuliah_cpl')->truncate();
        $existingMataKuliahIds = DB::table('bs_mata_kuliah')->pluck('id')->all();
        $existingMataKuliahIds = array_flip($existingMataKuliahIds);

        $data = array_values(array_filter([
            ['mk_id' => 5, 'cpl_id' => 4],
            ['mk_id' => 5, 'cpl_id' => 5],
            ['mk_id' => 6, 'cpl_id' => 4],
            ['mk_id' => 6, 'cpl_id' => 5],
            ['mk_id' => 6, 'cpl_id' => 6],
            ['mk_id' => 6, 'cpl_id' => 7],
            ['mk_id' => 6, 'cpl_id' => 8],
            ['mk_id' => 6, 'cpl_id' => 9],
            ['mk_id' => 6, 'cpl_id' => 10],
            ['mk_id' => 37, 'cpl_id' => 1],
            ['mk_id' => 37, 'cpl_id' => 3],
            ['mk_id' => 2, 'cpl_id' => 4],
            ['mk_id' => 2, 'cpl_id' => 5],
            ['mk_id' => 2, 'cpl_id' => 6],
            ['mk_id' => 2, 'cpl_id' => 7],
            ['mk_id' => 1, 'cpl_id' => 1],
            ['mk_id' => 1, 'cpl_id' => 4],
            ['mk_id' => 1, 'cpl_id' => 5],
            ['mk_id' => 1, 'cpl_id' => 8],
            ['mk_id' => 7, 'cpl_id' => 1],
            ['mk_id' => 3, 'cpl_id' => 1],
            ['mk_id' => 8, 'cpl_id' => 2],
            ['mk_id' => 8, 'cpl_id' => 3],
            ['mk_id' => 8, 'cpl_id' => 4],
            ['mk_id' => 8, 'cpl_id' => 5],
            ['mk_id' => 8, 'cpl_id' => 7],
            ['mk_id' => 8, 'cpl_id' => 9],
            ['mk_id' => 8, 'cpl_id' => 10],
            ['mk_id' => 4, 'cpl_id' => 2],
            ['mk_id' => 4, 'cpl_id' => 4],
            ['mk_id' => 4, 'cpl_id' => 5],
            ['mk_id' => 9, 'cpl_id' => 2],
            ['mk_id' => 9, 'cpl_id' => 3],
            ['mk_id' => 9, 'cpl_id' => 4],
            ['mk_id' => 9, 'cpl_id' => 5],
            ['mk_id' => 10, 'cpl_id' => 2],
            ['mk_id' => 10, 'cpl_id' => 3],
            ['mk_id' => 10, 'cpl_id' => 4],
            ['mk_id' => 10, 'cpl_id' => 5],
            ['mk_id' => 11, 'cpl_id' => 2],
            ['mk_id' => 11, 'cpl_id' => 3],
            ['mk_id' => 11, 'cpl_id' => 4],
            ['mk_id' => 11, 'cpl_id' => 5],
            ['mk_id' => 12, 'cpl_id' => 4],
            ['mk_id' => 12, 'cpl_id' => 9],
            ['mk_id' => 13, 'cpl_id' => 2],
            ['mk_id' => 13, 'cpl_id' => 3],
            ['mk_id' => 13, 'cpl_id' => 4],
            ['mk_id' => 13, 'cpl_id' => 5],
            ['mk_id' => 13, 'cpl_id' => 6],
            ['mk_id' => 13, 'cpl_id' => 7],
            ['mk_id' => 13, 'cpl_id' => 9],
            ['mk_id' => 13, 'cpl_id' => 10],
            ['mk_id' => 14, 'cpl_id' => 2],
            ['mk_id' => 14, 'cpl_id' => 3],
            ['mk_id' => 14, 'cpl_id' => 4],
            ['mk_id' => 14, 'cpl_id' => 5],
            ['mk_id' => 15, 'cpl_id' => 2],
            ['mk_id' => 15, 'cpl_id' => 3],
            ['mk_id' => 15, 'cpl_id' => 4],
            ['mk_id' => 15, 'cpl_id' => 5],
            ['mk_id' => 15, 'cpl_id' => 7],
            ['mk_id' => 15, 'cpl_id' => 9],
            ['mk_id' => 15, 'cpl_id' => 10],
            ['mk_id' => 16, 'cpl_id' => 2],
            ['mk_id' => 16, 'cpl_id' => 4],
            ['mk_id' => 16, 'cpl_id' => 5],
            ['mk_id' => 17, 'cpl_id' => 2],
            ['mk_id' => 17, 'cpl_id' => 3],
            ['mk_id' => 18, 'cpl_id' => 2],
            ['mk_id' => 18, 'cpl_id' => 3],
            ['mk_id' => 18, 'cpl_id' => 4],
            ['mk_id' => 18, 'cpl_id' => 5],
            ['mk_id' => 19, 'cpl_id' => 1],
            ['mk_id' => 19, 'cpl_id' => 2],
            ['mk_id' => 19, 'cpl_id' => 4],
            ['mk_id' => 19, 'cpl_id' => 5],
            ['mk_id' => 20, 'cpl_id' => 2],
            ['mk_id' => 20, 'cpl_id' => 3],
            ['mk_id' => 20, 'cpl_id' => 4],
            ['mk_id' => 20, 'cpl_id' => 5],
            ['mk_id' => 21, 'cpl_id' => 2],
            ['mk_id' => 21, 'cpl_id' => 3],
            ['mk_id' => 21, 'cpl_id' => 4],
            ['mk_id' => 21, 'cpl_id' => 5],
            ['mk_id' => 22, 'cpl_id' => 4],
            ['mk_id' => 22, 'cpl_id' => 5],
            ['mk_id' => 23, 'cpl_id' => 2],
            ['mk_id' => 23, 'cpl_id' => 3],
            ['mk_id' => 23, 'cpl_id' => 4],
            ['mk_id' => 23, 'cpl_id' => 8],
            ['mk_id' => 24, 'cpl_id' => 2],
            ['mk_id' => 24, 'cpl_id' => 4],
            ['mk_id' => 24, 'cpl_id' => 5],
            ['mk_id' => 25, 'cpl_id' => 1],
            ['mk_id' => 25, 'cpl_id' => 4],
            ['mk_id' => 25, 'cpl_id' => 6],
            ['mk_id' => 25, 'cpl_id' => 8],
            ['mk_id' => 26, 'cpl_id' => 2],
            ['mk_id' => 26, 'cpl_id' => 3],
            ['mk_id' => 26, 'cpl_id' => 4],
            ['mk_id' => 26, 'cpl_id' => 5],
            ['mk_id' => 26, 'cpl_id' => 7],
            ['mk_id' => 26, 'cpl_id' => 9],
            ['mk_id' => 27, 'cpl_id' => 4],
            ['mk_id' => 27, 'cpl_id' => 5],
            ['mk_id' => 27, 'cpl_id' => 7],
            ['mk_id' => 28, 'cpl_id' => 2],
            ['mk_id' => 28, 'cpl_id' => 3],
            ['mk_id' => 28, 'cpl_id' => 5],
            ['mk_id' => 30, 'cpl_id' => 2],
            ['mk_id' => 30, 'cpl_id' => 3],
            ['mk_id' => 30, 'cpl_id' => 4],
            ['mk_id' => 30, 'cpl_id' => 5],
            ['mk_id' => 29, 'cpl_id' => 2],
            ['mk_id' => 29, 'cpl_id' => 3],
            ['mk_id' => 29, 'cpl_id' => 4],
            ['mk_id' => 29, 'cpl_id' => 5]

        ], static fn (array $item): bool => isset($existingMataKuliahIds[$item['mk_id']])));

        DB::table('bs_mata_kuliah_cpl')->insert($data);
    }
}
