@extends('capstone::layouts.app')
@section('title','Dashboard')
@section('content')
<div x-data="capstoneDashboard">
@include('capstone::partials.loading')
<div x-show="!loading && !error" x-cloak class="flex flex-col space-y-6">
    <div><h1 class="text-2xl font-bold tracking-tight">Halo, {{ explode(' ', $actor['name'])[0] }}!</h1></div>
    <div class="bg-white rounded-xl border border-gray-100 p-5 shadow-sm"><div class="mb-4"><h2 class="text-base font-semibold text-gray-800">Status Group</h2><p class="text-sm text-gray-400 mt-0.5">Periode <span class="font-medium text-gray-600" x-text="data.group_period?.name || data.active_periods?.[0]?.name || 'N/A'"></span></p></div><div class="flex items-center justify-between gap-2">
        @foreach(['PDC1'=>'PDC 1','SEMPRO'=>'Seminar Proposal','PDC2'=>'PDC 2','TA_DRAFT'=>'TA Draft','EXPO'=>'Expo','TA'=>'Sidang TA'] as $phase=>$label)
        <div class="flex flex-col items-center gap-2 flex-1 cursor-pointer" :title="(workflow.phases || []).find(p=>p.phase==='{{ $phase }}')?.status || 'locked'"><div class="w-10 h-10 rounded-lg flex items-center justify-center border-2 transition-all" :class="[(workflow.phases || []).find(p=>p.phase==='{{ $phase }}')?.status==='completed' ? 'bg-emerald-50 border-emerald-500 text-emerald-600' : ((workflow.phases || []).find(p=>p.phase==='{{ $phase }}')?.status || 'locked')==='locked' ? 'bg-gray-100 border-gray-200 text-gray-400' : 'bg-white border-primary-500 text-primary-500',workflow.current_phase==='{{ $phase }}' && 'ring-2 ring-primary-500/30']"><x-capstone::icon name="Check" class="h-5 w-5" x-show="(workflow.phases || []).find(p=>p.phase==='{{ $phase }}')?.status==='completed'" /><x-capstone::icon name="Lock" class="h-4 w-4" x-show="((workflow.phases || []).find(p=>p.phase==='{{ $phase }}')?.status || 'locked')==='locked'" /><x-capstone::icon name="Circle" class="h-5 w-5" x-show="!['locked','completed'].includes((workflow.phases || []).find(p=>p.phase==='{{ $phase }}')?.status || 'locked')" /></div><span class="text-xs font-medium text-center leading-tight text-gray-500">{{ $label }}</span></div>
        @endforeach
    </div></div>
    <div class="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <x-capstone::card class="h-full" x-show="group?.id && group?.status"><div class="p-5 space-y-4"><x-capstone::badge variant="outline" x-show="workflow.current_phase" x-text="workflow.current_phase" class="text-xs font-medium h-6 px-2.5 bg-primary-50 text-primary-700 border-primary-200" /><div><h3 class="text-lg font-semibold text-gray-800 leading-snug line-clamp-2" x-text="data.title || group?.title?.title || 'Belum ada judul'"></h3><p class="text-sm text-gray-400 mt-1 font-mono" x-text="(group?.period?.name || '')+'K'+(group?.id || '')"></p></div><div class="space-y-1.5"><div class="flex items-center justify-between text-sm"><span class="text-gray-500">Progress</span><span class="font-medium text-gray-700" x-text="progress+'%'"></span></div><div class="bg-primary/20 h-2 rounded-full overflow-hidden"><div class="bg-primary h-full transition-all" :style="{width:progress+'%'}"></div></div></div><div class="flex items-center gap-3"><x-capstone::icon name="Users" class="h-4 w-4 text-gray-400" /><div class="flex -space-x-2"><template x-for="member in (group?.members || []).slice(0,4)" :key="member.id"><span class="h-7 w-7 rounded-full border-2 border-white bg-primary-100 text-primary-700 text-[10px] flex items-center justify-center" x-text="(member.student?.name || member.student?.user?.name || '?').split(' ').map(n=>n[0]).join('').slice(0,2).toUpperCase()"></span></template></div><span class="text-xs text-gray-400" x-text="(group?.members?.length || 0)+' anggota'"></span></div><hr><div class="space-y-2"><template x-for="supervisor in [group?.supervisor1,group?.supervisor2].filter(Boolean)"><div class="flex items-center gap-2"><span class="h-6 w-6 rounded-full bg-gray-100 text-gray-600 text-[10px] flex items-center justify-center" x-text="(supervisor.name || supervisor.user?.name || '?').slice(0,2).toUpperCase()"></span><span class="text-sm text-gray-600" x-text="supervisor.name || supervisor.user?.name"></span></div></template></div></div></x-capstone::card>
        <div x-show="!group?.id || !group?.status" class="rounded-xl border bg-white shadow-sm flex flex-col items-center justify-center p-8 text-center"><p class="font-semibold mb-4">Anda belum memiliki grup yang disetujui</p><x-capstone::button href="/mahasiswa/group" variant="outline" size="sm">Buat / Cari Kelompok</x-capstone::button></div>
        @include('capstone::partials.mini-calendar')
    </div>
    @include('capstone::pages.mahasiswa.dashboard._documents')
    <div>
        <div class="lg:col-span-1"><x-capstone::card class="h-full"><div class="p-5"><h3 class="text-base font-semibold text-gray-800 mb-4">Akses Cepat</h3><div class="grid grid-cols-2 gap-3">@foreach([['Jadwal','schedule','CalendarDays','blue'],['Dokumen','documents','FileText','amber'],['Nilai','grades','GraduationCap','emerald'],['Expo','expo','Presentation','violet']] as [$label,$href,$icon,$color])<x-capstone::feature-link :href="'/mahasiswa/'.$href" class="w-full h-auto py-4 px-3 flex flex-col items-center gap-2.5 rounded-xl border transition-all hover:shadow-sm bg-{{ $color }}-50 text-{{ $color }}-600 border-{{ $color }}-100 hover:border-{{ $color }}-300"><span class="p-2 rounded-lg bg-{{ $color }}-100"><x-capstone::icon :name="$icon" class="h-5 w-5" /></span><span class="text-sm font-medium">{{ $label }}</span></x-capstone::feature-link>@endforeach</div></div></x-capstone::card></div>
    </div>
</div>
</div>
@endsection
