@extends('capstone::layouts.app')
@section('title','Titles Marketplace')
@section('content')
<div x-data="studentMarketplace" class="space-y-6">@include('capstone::partials.loading')
<div x-show="!loading && !error" x-cloak class="space-y-6"><div class="flex flex-col md:flex-row md:items-center justify-between gap-4"><div><h1 class="text-3xl font-bold tracking-tight">Titles Marketplace</h1><p class="text-muted-foreground">Temukan topik skripsi atau bergabung dengan ide mahasiswa lain.</p></div><x-capstone::badge variant="outline" class="text-sm px-3 py-1">Period: <span x-text="period?.name"></span></x-capstone::badge></div>
<x-capstone::alert title="View-Only Mode" variant="destructive" icon="Lock" x-show="period?.is_finalized">Pendaftaran periode sudah ditutup. Anda masih bisa melihat judul sebagai arsip, tetapi tidak dapat melakukan bidding atau meminta bergabung.</x-capstone::alert>
<x-capstone::alert title="No Group Yet" x-show="!group">Anda harus <x-capstone::feature-link href="/mahasiswa/group" class="underline font-medium">membuat kelompok</x-capstone::feature-link> terlebih dahulu sebelum bisa melakukan bidding.</x-capstone::alert>
<x-capstone::alert title="Leader Only" icon="Lock" x-show="group && !isLeader">Hanya ketua kelompok yang dapat bidding judul dosen. Minta ketua kelompok Anda untuk melakukan bidding.</x-capstone::alert>
<x-capstone::alert title="Bidding Locked" variant="destructive" icon="Lock" x-show="group && !group.is_solo && members.length < minMembers">Kelompok Anda memiliki <span x-text="members.length"></span> anggota. Minimal <span x-text="minMembers"></span> anggota diperlukan untuk bidding judul dosen. Tambahkan anggota di <x-capstone::feature-link href="/mahasiswa/group" class="underline font-bold">Grup Saya</x-capstone::feature-link>.</x-capstone::alert>
<x-capstone::alert title="Belum Bisa Bidding Judul Dosen" variant="destructive" icon="Lock" x-show="group?.is_solo && members.length < minMembers">Kelompok solo Anda memiliki <span x-text="members.length"></span> dari minimal <span x-text="minMembers"></span> anggota. Untuk membuka bidding judul dosen, tambah anggota di <x-capstone::feature-link href="/mahasiswa/group" class="underline font-bold">Grup Saya</x-capstone::feature-link> hingga mencapai minimal. Sementara itu, Anda tetap dapat <x-capstone::feature-link href="/mahasiswa/propose-title" class="underline font-medium">mengajukan judul sendiri</x-capstone::feature-link>.</x-capstone::alert>
<x-capstone::alert title="Bidding Dinonaktifkan" variant="destructive" icon="Lock" x-show="group && (group.title_id || group.status==='READY_FOR_FINALIZATION')">Kelompok Anda sudah memiliki judul yang disetujui dan terkunci untuk finalisasi, sehingga tombol bidding judul dosen dinonaktifkan. Kelola kelompok Anda di <x-capstone::feature-link href="/mahasiswa/group" class="underline font-bold">Grup Saya</x-capstone::feature-link> atau pantau di <x-capstone::feature-link href="/mahasiswa/propose-title" class="underline font-medium">Lihat Proposal</x-capstone::feature-link>.</x-capstone::alert>
<div class="flex flex-col sm:flex-row gap-4 items-start sm:items-center"><div class="relative flex-1 w-full"><x-capstone::icon name="Search" class="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" /><x-capstone::input aria-label="Search titles" placeholder="Search titles, lecturers, or student ideas..." x-model.debounce.200ms="search" class="pl-9" /></div><div class="flex flex-wrap items-center gap-2"><span class="text-sm font-medium mr-1">Filter Tags:</span><template x-for="spec in specs" :key="spec"><button type="button" class="inline-flex items-center rounded-md border px-2 py-0.5 text-xs font-medium cursor-pointer select-none" :aria-pressed="filterSpecs.includes(spec)" :class="filterSpecs.includes(spec) ? 'bg-primary text-primary-foreground border-transparent' : 'text-foreground'" @click="toggleSpec(spec)" x-text="spec"></button></template></div></div>
<div class="space-y-4"><div role="tablist" aria-label="Title sources" class="grid w-full grid-cols-2 lg:w-[400px] bg-muted text-muted-foreground h-9 rounded-lg p-[3px]">
@foreach(['lecturer'=>['BookOpen','Lecturer Offered'],'student'=>['Lightbulb','Student Ideas']] as $tab=>$meta)<button type="button" role="tab" id="tab-{{ $tab }}" aria-controls="panel-{{ $tab }}" :aria-selected="tab==='{{ $tab }}'" @click="tab='{{ $tab }}'" class="flex items-center justify-center gap-2 rounded-md text-sm font-medium" :class="tab==='{{ $tab }}' && 'bg-background text-foreground shadow-sm'"><x-capstone::icon :name="$meta[0]" />{{ $meta[1] }}</button>@endforeach
</div>
@include('capstone::pages.mahasiswa.titles.lecturer-titles')
@include('capstone::pages.mahasiswa.titles.student-ideas')
</div></div>
@include('capstone::pages.mahasiswa.titles.join-dialog')
</div>
@endsection
