@extends('capstone::layouts.app')
@section('title','Title Bidding')
@section('content')
<div x-data="studentBidding" class="space-y-6">@include('capstone::partials.loading')
<div x-show="!loading && !error" x-cloak class="space-y-6"><div class="flex flex-wrap justify-between items-start gap-4"><div><h1 class="text-3xl font-bold tracking-tight">Title Bidding</h1><p class="text-muted-foreground" x-text="isLeader?'Kelola ranking judul TA Anda. Gunakan panah untuk mengubah urutan prioritas.':'Submit and manage your title bids.'"></p></div><div x-show="isLeader" class="flex flex-wrap items-center gap-3"><x-capstone::badge variant="outline" class="text-sm px-3 py-1"><span x-text="total+'/3 slots used'"></span></x-capstone::badge><x-capstone::button @click="open()" ::disabled="!canSubmit || !availableTitles.length">Submit Bid</x-capstone::button><x-capstone::button x-show="changed" @click="saveOrder()" ::disabled="saving || !canReorder"><x-capstone::icon name="Save" />Simpan Urutan</x-capstone::button></div></div>
<x-capstone::alert title="No Group" icon="AlertTriangle" x-show="!group">You need to join or create a group first before bidding on titles.</x-capstone::alert>
<x-capstone::alert title="Leader Only" icon="Lock" x-show="group && !isLeader">Only the group leader can submit and manage title bids. Contact your group leader for bidding.</x-capstone::alert>
<x-capstone::alert title="Bidding Terkunci" icon="Lock" x-show="!canSubmit && flow?.reason && !(group?.is_solo && flow.reason==='INSUFFICIENT_MEMBERS')"><span x-text="reasonText[flow?.reason] || 'Bidding tidak tersedia untuk kondisi kelompok saat ini.'"></span></x-capstone::alert>
<x-capstone::alert title="Belum Bisa Bidding Judul Dosen" variant="destructive" icon="Lock" x-show="!canSubmit && group?.is_solo && flow?.reason==='INSUFFICIENT_MEMBERS'">Kelompok solo Anda memiliki <span x-text="members.length"></span> dari minimal <span x-text="minMembers"></span> anggota. Untuk membuka bidding judul dosen, tambah anggota di <x-capstone::feature-link href="/mahasiswa/group" class="underline font-bold">Grup Saya</x-capstone::feature-link> hingga mencapai minimal. Sementara itu, Anda tetap dapat <x-capstone::feature-link href="/mahasiswa/propose-title" class="underline font-medium">mengajukan judul sendiri</x-capstone::feature-link>.</x-capstone::alert>
<x-capstone::alert title="Limit Reached" icon="AlertTriangle" x-show="total>=3">You have used all 3 title slots (bids + proposals combined). Delete an existing bid to make room for a new one.</x-capstone::alert>
<x-capstone::alert title="Proposal Aktif" icon="Lock" variant="destructive" x-show="proposals.length">Kelompok Anda memiliki proposal yang sedang diproses. Tidak dapat mengajukan bid baru. <x-capstone::feature-link href="/mahasiswa/propose-title" class="underline ml-1">Lihat Proposal</x-capstone::feature-link></x-capstone::alert>
<div x-show="!bids.length && !proposals.length" class="text-center py-12 border rounded-lg border-dashed"><x-capstone::icon name="Gavel" class="h-12 w-12 mx-auto mb-4 opacity-50 text-muted-foreground" /><h2 class="text-xl font-bold mb-2">No Bids Yet</h2><p class="text-muted-foreground mb-4 max-w-md mx-auto">Submit a bid to express your interest in a title. You can rank multiple titles by priority.</p></div>
@include('capstone::pages.mahasiswa.bidding.proposals')
@include('capstone::pages.mahasiswa.bidding.bids')
</div>@include('capstone::pages.mahasiswa.bidding.form')</div>
@endsection
