<x-capstone::dialog id="admin-ta-form" title="Schedule TA Defense" description="Create a new TA defense schedule for selected students. Examiners cannot be supervisors of the group." width="sm:max-w-150">
    <div x-show="formError" role="alert" class="mt-4 rounded-lg border border-destructive/40 bg-destructive/5 text-destructive p-3 text-sm" x-text="formError"></div>
    <form @submit.prevent="save"><div class="grid gap-4 py-4">
        <div x-show="!editing"><x-capstone::field name="period_id" label="Period" type="select" :options="[''=>'Select period']" @change="periodChanged" required><template x-for="period in periods" :key="period.id"><option :value="String(period.id)" x-text="period.name+(period.is_active?' (active)':'')"></option></template></x-capstone::field></div>
        <x-capstone::field name="group_id" label="Group" type="select" :options="[''=>'Select group']" @change="form.student_ids=[]" ::disabled="!!editing || !form.period_id || eligibleLoading" required><template x-for="group in eligible" :key="group.id"><option :value="String(group.id)" x-text="'Group '+group.id+(group.code?' ('+group.code+')':'')"></option></template></x-capstone::field>
        <p x-show="eligibleLoading" class="text-sm text-muted-foreground">Loading students...</p>
        <div x-show="form.group_id" class="space-y-2"><p class="text-sm font-medium">Students <span class="text-muted-foreground text-xs">(select at least one)</span></p><div class="border rounded-md p-3 space-y-2 max-h-48 overflow-y-auto"><p x-show="!members.length" class="text-sm text-muted-foreground">No students in this group.</p><template x-for="member in members" :key="member.student.id"><label class="flex items-center space-x-3" :class="!member.is_ready_for_sidang?'opacity-50':''"><input type="checkbox" x-model="form.student_ids" :value="String(member.student.id)" :disabled="member.is_already_selected || !member.is_ready_for_sidang" class="size-4 accent-primary rounded border"><span class="text-sm flex-1"><span x-text="member.student.name"></span><span class="text-muted-foreground text-xs ml-2" x-text="member.student.nim"></span></span><span class="text-xs text-muted-foreground" x-text="member.is_already_selected?'Already selected':member.has_active_defense?'Already scheduled':member.is_ready_for_sidang?'Ready':member.status_text"></span></label></template></div><p x-show="errors.student_ids" x-text="errors.student_ids?.[0]" class="text-sm text-destructive"></p></div>
        <div class="grid grid-cols-1 sm:grid-cols-2 gap-4"><x-capstone::field name="date" label="Date" type="date" ::min="today" required /><x-capstone::field name="eoffice_ruangan_id" label="Location (Ruangan EOffice)" type="select" :options="[''=>'Select room...']" required><template x-for="room in eofficeRooms" :key="room.id"><option :value="String(room.id)" x-text="room.nama+(room.kapasitas?' ('+room.kapasitas+')':'')"></option></template></x-capstone::field></div>
        <div class="grid grid-cols-2 gap-4"><x-capstone::field name="start_time" label="Start Time" type="time" required /><x-capstone::field name="end_time" label="End Time" type="time" required /></div>
        <div class="grid grid-cols-1 sm:grid-cols-2 gap-4">@foreach([1,2] as $number)<x-capstone::field name="examiner_{{ $number }}_id" label="Examiner {{ $number }}" type="select" :options="[''=>'Select examiner']" required><template x-for="lecturer in lecturers" :key="lecturer.id"><option :value="String(lecturer.id)" :disabled="supervisorIds.includes(Number(lecturer.id))" x-text="lecturer.name"></option></template></x-capstone::field>@endforeach</div>
        <x-capstone::field name="notes" label="Notes" type="textarea" placeholder="Additional notes..." maxlength="1000" />
    </div><div class="flex justify-end gap-2"><x-capstone::button variant="outline" @click="document.getElementById('admin-ta-form').close()" ::disabled="saving">Cancel</x-capstone::button><x-capstone::button type="submit" ::disabled="saving || eligibleLoading"><x-capstone::icon name="Loader2" class="h-4 w-4 animate-spin" x-show="saving" /><span x-text="saving?'Saving...':editing?'Update Schedule':'Create Schedule'"></span></x-capstone::button></div></form>
</x-capstone::dialog>
