<div class="mt-4 overflow-x-auto"><table class="w-full min-w-[960px] caption-bottom text-sm"><thead><tr class="bg-[#F8F9FB] text-[13px] font-medium text-[#666D80]"><th class="w-10 px-2 py-3"></th><th class="px-4 py-3 font-medium">No</th><th class="px-4 py-3 font-medium">Student</th><th class="px-4 py-3 font-medium">NIM</th><th class="px-4 py-3 font-medium">Group</th><th class="px-4 py-3 font-medium">Date</th><th class="px-4 py-3 font-medium">Time</th><th class="px-4 py-3 font-medium">Location</th><th class="px-4 py-3 font-medium">Examiners</th><th class="px-4 py-3 font-medium">Status</th><th class="px-5 py-3 text-right font-medium">Actions</th></tr></thead>
    <template x-for="(s,i) in visible" :key="s.id"><tbody><tr class="bg-white cursor-pointer hover:bg-muted/30" @click="toggle(s.id)" :class="s.status==='CANCELLED'?'text-muted-foreground/60':''">
        <td class="p-2"><button type="button" class="h-8 w-8 flex items-center justify-center rounded-md hover:bg-accent" @click.stop="toggle(s.id)" :aria-expanded="expanded.includes(s.id)" aria-label="Schedule details"><x-capstone::icon name="ChevronDown" class="h-4 w-4 text-muted-foreground" ::class="expanded.includes(s.id)?'rotate-180':''" /></button></td>
        <td class="px-4 py-4 text-foreground" x-text="(currentPage-1)*Number(perPage)+i+1"></td>
        <td class="px-4 py-4"><span class="font-semibold" x-text="students(s)[0]?.name || 'N/A'"></span><span x-show="students(s).length>1" class="text-xs text-muted-foreground ml-1" x-text="'+'+(students(s).length-1)+' more'"></span></td>
        <td class="px-4 py-4 text-sm font-mono tabular-nums text-muted-foreground" x-text="students(s)[0]?.nim || '-'"></td><td class="px-4 py-4 text-sm tabular-nums text-muted-foreground" x-text="s.group?.code || '#'+s.group_id"></td>
        <td class="px-4 py-4 text-sm whitespace-nowrap font-mono tabular-nums text-muted-foreground" x-text="date(s.date)"></td><td class="px-4 py-4 text-sm whitespace-nowrap font-mono tabular-nums text-muted-foreground"><span x-text="s.start_time?.slice(0,5)"></span><span class="text-muted-foreground/40 mx-0.5">–</span><span x-text="s.end_time?.slice(0,5)"></span></td><td class="px-4 py-4 text-sm text-muted-foreground" x-text="location(s)"></td><td class="px-4 py-4 text-xs text-muted-foreground"><p x-text="s.examiner1?.name || '—'"></p><p x-text="s.examiner2?.name || '—'"></p></td>
        <td class="px-4 py-4"><span class="inline-flex items-center rounded-full px-2.5 py-0.5 text-xs font-medium" :class="statusBadgeClass(s.status)" x-text="statusLabel(s.status)"></span></td>
        <td class="px-5 py-4 text-right"><div class="flex items-center justify-end" @click.stop><button type="button" @click="openRowMenu($event,s)" aria-label="Aksi" aria-haspopup="menu" class="rounded-md p-1.5 text-[#666D80] hover:bg-muted"><x-capstone::icon name="Ellipsis" class="size-5" /></button></div></td>
    </tr><tr x-show="expanded.includes(s.id)" class="bg-muted/30 border-b"><td colspan="11" class="p-4"><div class="grid grid-cols-1 lg:grid-cols-2 gap-6"><div class="space-y-2"><h3 class="text-[11px] font-semibold uppercase tracking-wider text-muted-foreground/70">Defense Info</h3><p class="text-[12px] font-medium text-foreground/80" x-text="s.group?.title?.title || 'No title assigned'"></p><div class="space-y-1.5">@foreach(['Examiner 1'=>'s.examiner1?.name','Examiner 2'=>'s.examiner2?.name','Eval Deadline'=>'date(s.evaluation_deadline)'] as $label=>$expression)<div class="flex items-center justify-between"><span class="text-muted-foreground/70 text-[12px]">{{ $label }}</span><span class="text-[12px] font-medium text-foreground/80" x-text="{{ $expression }} || '—'"></span></div>@endforeach</div></div><div class="space-y-2"><h3 class="text-[11px] font-semibold uppercase tracking-wider text-muted-foreground/70">Student Info</h3><div class="space-y-1.5"><template x-for="(student,index) in students(s)" :key="student.id"><div class="border-b border-border/50 last:border-0 pb-1.5 last:pb-0"><div class="flex items-center justify-between"><span class="text-muted-foreground/70 text-[12px]" x-text="'Name'+(index?' #'+(index+1):'')"></span><span class="text-[12px] font-medium text-foreground/80" x-text="student.name"></span></div><div class="flex items-center justify-between"><span class="text-muted-foreground/70 text-[12px]">NIM</span><span class="text-[12px] text-muted-foreground font-mono tabular-nums" x-text="student.nim"></span></div></div></template>@foreach(['Group'=>"'#'+s.group_id",'Period'=>"s.period?.name || s.group?.period?.name",'Notes'=>'s.notes'] as $label=>$expression)<div class="flex items-center justify-between"><span class="text-muted-foreground/70 text-[12px]">{{ $label }}</span><span class="text-[12px] text-muted-foreground" x-text="{{ $expression }} || '—'"></span></div>@endforeach</div></div></div></td></tr></tbody></template>
</table></div>
<div x-show="filtered.length" x-cloak class="flex flex-wrap items-center justify-between gap-3 border-t border-border px-5 py-3.5 text-sm">
    <div class="flex items-center gap-3">
        <label class="inline-flex items-center gap-0 overflow-hidden rounded-lg border border-input bg-white text-[13px]">
            <span class="px-2.5 text-muted-foreground">Per page</span>
            <select x-model.number="perPage" @change="page=1" aria-label="Baris per halaman" class="border-l border-input bg-transparent px-2 py-1.5 font-medium outline-none"><option>10</option><option>25</option><option>50</option></select>
        </label>
        <span class="text-foreground"><span x-text="'Showing '+showingFrom+' to '+showingTo+' of, '+filtered.length+' results'"></span></span>
    </div>
    <div class="flex items-center gap-1.5">
        <button type="button" @click="goPage(currentPage-1)" :disabled="currentPage<=1" aria-label="Previous page" class="inline-flex size-8 items-center justify-center rounded-lg border border-input bg-white text-muted-foreground disabled:opacity-40"><x-capstone::icon name="ChevronLeft" class="size-4" /></button>
        <template x-for="(n,i) in pageNumbers" :key="n">
            <span class="flex items-center gap-1.5">
                <span x-show="i>0 && n-pageNumbers[i-1]>1" class="px-1 text-muted-foreground">...</span>
                <button type="button" @click="goPage(n)" x-text="n" class="inline-flex size-8 items-center justify-center rounded-lg border text-sm" :class="currentPage===n?'border-[#1E2A5A] bg-[#1E2A5A] font-semibold text-white':'border-input bg-white text-foreground hover:bg-accent'"></button>
            </span>
        </template>
        <button type="button" @click="goPage(currentPage+1)" :disabled="currentPage>=totalPages" aria-label="Next page" class="inline-flex size-8 items-center justify-center rounded-lg border border-input bg-white text-muted-foreground disabled:opacity-40"><x-capstone::icon name="ChevronRight" class="size-4" /></button>
    </div>
</div>
