<div x-show="view==='table'" x-cloak class="space-y-4">
    <div class="flex flex-wrap items-center gap-2">
        <x-capstone::input x-model.debounce.200ms="search" @input="page=1" placeholder="Search schedules..." class="max-w-sm" aria-label="Search schedules" />
        <select x-model="typeFilter" @change="page=1" class="h-9 rounded-md border px-3 text-sm" aria-label="Schedule type"><option value="all">All Types</option>@foreach(['BIMBINGAN','SEMPRO','EXPO','TA_DEFENSE'] as $type)<option>{{ $type }}</option>@endforeach</select>
        <select x-model="statusFilter" @change="page=1" class="h-9 rounded-md border px-3 text-sm" aria-label="Schedule status"><option value="all">All Statuses</option>@foreach(['PENDING','PENDING_APPROVAL','SCHEDULED','APPROVED','COMPLETED','CANCELLED','REJECTED'] as $status)<option>{{ $status }}</option>@endforeach</select>
    </div>
    <div class="rounded-md border overflow-x-auto"><table class="w-full text-sm"><thead><tr class="border-b text-left">
        <th class="p-4 font-medium">Type</th><th class="p-4 font-medium"><button type="button" @click="sortDirection*=-1">Date &amp; Time ↕</button></th>@foreach(['Period','Group','Student','Room','Status','Actions'] as $label)<th class="p-4 font-medium">{{ $label }}</th>@endforeach
    </tr></thead><tbody><template x-for="event in visibleRows" :key="event._key"><tr class="border-b hover:bg-muted/50 cursor-pointer" @click="detail(event)">
        <td class="p-4"><span class="rounded-md px-2 py-1 text-xs whitespace-nowrap" :class="color(event.type)" x-text="label(event.type)"></span></td>
        <td class="p-4 whitespace-nowrap"><p x-text="date(event.date)"></p><p class="text-xs text-muted-foreground" x-text="time(event)"></p></td><td class="p-4" x-text="event.period_name || '-'"></td>
        <td class="p-4 font-medium" x-text="event.group?.title?.title || '-'"></td><td class="p-4" x-text="students(event) || '-'"></td><td class="p-4 text-muted-foreground" x-text="event.room || (event.mode==='online' ? 'Online' : '-')"></td>
        <td class="p-4"><span class="rounded-full px-2 py-0.5 text-xs capitalize" :class="statusColor(event.status)" x-text="(event.status || 'SCHEDULED').toLowerCase()"></span></td><td class="p-4"><div class="flex items-center gap-1">@include('capstone::partials.schedule-actions')<x-capstone::button variant="ghost" size="sm" x-show="!canApprove(event)" @click.stop="detail(event)"><x-capstone::icon name="Eye" />View</x-capstone::button></div></td>
    </tr></template><tr x-show="!tableRows.length"><td colspan="8" class="h-24 text-center text-muted-foreground">No results.</td></tr></tbody></table></div>
    <div class="flex flex-wrap items-center justify-between gap-4 text-sm"><span class="text-muted-foreground" x-text="tableRows.length+' schedule(s)'"></span><div class="flex items-center gap-3"><label>Rows per page <select x-model.number="perPage" @change="page=1" class="rounded-md border p-1"><option>10</option><option>20</option><option>50</option></select></label><span x-text="'Page '+currentPage+' of '+totalPages"></span><x-capstone::button variant="outline" size="icon" @click="page=currentPage-1" ::disabled="currentPage<=1" aria-label="Previous page"><x-capstone::icon name="ChevronLeft" /></x-capstone::button><x-capstone::button variant="outline" size="icon" @click="page=currentPage+1" ::disabled="currentPage>=totalPages" aria-label="Next page"><x-capstone::icon name="ChevronRight" /></x-capstone::button></div></div>
</div>
