@extends('capstone::layouts.app')
@section('title','Detail User')
@section('content')
<div x-data="adminUsers('detail')" class="space-y-6">
    <div class="flex flex-wrap items-center justify-between gap-3"><x-capstone::button href="/admin/users" variant="outline"><x-capstone::icon name="ChevronLeft" class="h-4 w-4" />Kembali</x-capstone::button><template x-if="user"><div class="flex gap-2"><a x-show="user.can_edit" :href="userUrl(user,true)" class="rounded-md border px-4 py-2 text-sm font-medium">Edit</a><x-capstone::button variant="destructive" x-show="user.can_delete" @click="confirmDelete([user])">Hapus</x-capstone::button></div></template></div>
    @include('capstone::partials.loading')
    <template x-if="user && !loading && !error"><div class="space-y-6">
        <div class="flex items-center gap-5"><span class="flex h-16 w-16 shrink-0 items-center justify-center rounded-full bg-primary/10 text-xl font-semibold text-primary" x-text="initials(user)"></span><div><h1 class="text-3xl font-semibold" x-text="user.name"></h1><div class="mt-2 flex gap-2"><span x-show="user.is_sso" class="rounded border bg-primary/5 px-2 py-1 text-xs text-primary">SSO</span><span class="rounded-full px-2 py-1 text-xs" :class="user.status==='active'?'bg-green-100 text-green-700':'bg-red-100 text-red-700'" x-text="user.status==='active'?'Aktif':'Ditangguhkan'"></span></div></div></div>
        <dl class="grid gap-6 rounded-xl border bg-card p-6 md:grid-cols-2">@foreach(['email'=>'Email','nim'=>'NIM','nip'=>'NIP / Identitas Dosen','cohort_year'=>'Angkatan'] as $field=>$label)<div><dt class="text-sm text-muted-foreground">{{ $label }}</dt><dd class="mt-1 break-words text-sm font-medium" x-text="user.{{ $field }}||'-'"></dd></div>@endforeach<div><dt class="text-sm text-muted-foreground">Tanggal Daftar</dt><dd class="mt-1 text-sm font-medium" x-text="date(user.created_at)"></dd></div><div><dt class="text-sm text-muted-foreground">Aktivitas Terakhir</dt><dd class="mt-1 text-sm font-medium" x-text="date(user.last_login,true)"></dd></div></dl>
        <section class="grid gap-6 rounded-xl border bg-card p-6 md:grid-cols-2"><div><h2 class="text-xl font-semibold">Role &amp; Permissions</h2><p class="mt-2 text-sm text-muted-foreground">Manage roles and module permissions for each user.</p></div><div><h3 class="mb-3 text-sm font-medium">Access Role</h3><div class="flex flex-wrap gap-2"><template x-for="slug in user.roles" :key="slug"><span class="rounded-full border bg-primary/5 px-3 py-1 text-sm capitalize text-primary" x-text="slug"></span></template></div><p x-show="user.other_roles.length" class="mt-3 text-xs text-muted-foreground" x-text="'Role lainnya: '+user.other_roles.join(', ')"></p><a x-show="user.can_edit" :href="userUrl(user,true)" class="mt-4 inline-block text-sm text-primary hover:underline">Edit Role &amp; Profile</a></div></section>
        <p x-show="user.roles.includes('dosen') && !user.lecturer_id" class="rounded-lg border border-amber-200 bg-amber-50 p-4 text-sm text-amber-800">Profil dosen belum tersedia. Lengkapi NIP melalui Edit agar identitas akademik sesuai.</p>
    </div></template>
    @include('capstone::pages.admin.users.delete-dialog')
</div>
@endsection
