<div x-data="adminUsers('{{ $mode }}')" class="space-y-6">
    <div class="flex flex-wrap items-center justify-between gap-3"><x-capstone::button href="/admin/users" variant="outline"><x-capstone::icon name="ChevronLeft" class="h-4 w-4" />Kembali</x-capstone::button><x-capstone::button type="submit" form="user-form" ::disabled="loading || saving || !editable"><x-capstone::icon name="Save" class="h-4 w-4" /><span x-text="saving?'Menyimpan...':'Simpan'"></span></x-capstone::button></div>
    @include('capstone::partials.loading')
    <form id="user-form" @submit.prevent="save()" x-show="!loading && !error" x-cloak class="space-y-6">
        <p x-show="!editable" class="rounded-lg border bg-muted p-4 text-sm">Akun ini dikelola melalui administrator sistem.</p>
        <fieldset :disabled="saving || !editable" class="space-y-6">
            <section class="grid gap-8 rounded-xl border bg-card p-6 shadow-sm lg:grid-cols-[280px_1fr]"><div><span x-show="user?.is_sso" class="mb-3 inline-flex rounded border bg-primary/5 px-2 py-1 text-xs text-primary">SSO</span><h1 class="text-xl font-semibold">{{ $mode==='new'?'Tambah User Baru':'Detail User' }}</h1><p class="mt-2 text-sm text-muted-foreground">Informasi akun dan identitas akademik user.</p></div><div class="grid gap-6 md:grid-cols-2">
                <x-capstone::field name="name" label="Nama Lengkap" minlength="2" maxlength="100" required /><x-capstone::field name="email" label="Email" type="email" maxlength="255" required />
                <x-capstone::field name="password" label="{{ $mode==='new'?'Password':'Password Baru (Opsional)' }}" type="password" minlength="8" maxlength="255" autocomplete="new-password" :required="$mode==='new'" />
                <div x-show="hasLecturer"><x-capstone::field name="nip" label="NIP / Identitas Dosen" maxlength="100" x-bind:required="hasLecturer" /><p class="mt-1 text-xs text-muted-foreground">Digunakan untuk profil dosen dan akses bimbingan.</p></div>
                <div x-show="hasStudent"><x-capstone::field name="nim" label="NIM" minlength="8" maxlength="100" x-bind:required="hasStudent" /></div><div x-show="hasStudent"><x-capstone::field name="cohort_year" label="Angkatan" type="number" min="1900" :max="now()->year+1" x-bind:required="hasStudent" /></div>
            </div></section>
            <section class="grid gap-8 rounded-xl border bg-card p-6 shadow-sm lg:grid-cols-[280px_1fr]"><div><h2 class="text-xl font-semibold">Role &amp; Permissions</h2><p class="mt-2 text-sm text-muted-foreground">Manage roles and module permissions for each user.</p></div><div><fieldset class="space-y-3 rounded-lg border p-4"><legend class="px-1 text-sm font-medium">Access Role</legend>@foreach(['mahasiswa'=>'Mahasiswa','dosen'=>'Dosen','admin'=>'Admin'] as $slug=>$label)<label class="flex items-center gap-3 text-sm font-medium"><input type="checkbox" :checked="form.roles.includes('{{ $slug }}')" @change="toggleRole('{{ $slug }}',$event.target.checked)" class="accent-primary">{{ $label }}</label>@endforeach</fieldset><p class="mt-2 text-xs text-muted-foreground">Role mahasiswa berdiri sendiri. Role admin dan dosen dapat digabung.</p><p class="mt-2 text-sm text-destructive" x-text="errors.roles?.[0]"></p></div></section>
        </fieldset>
        <div x-show="errors.root" class="rounded-lg border border-red-200 bg-red-50 p-4 text-sm text-red-700" role="alert"><p x-text="errors.root"></p><template x-for="(messages,key) in errors" :key="key"><p x-show="key!=='root'" x-text="Array.isArray(messages)?messages.join(' '):''"></p></template></div>
    </form>
</div>
