@extends('capstone::layouts.app')
@section('title','Bank Asesmen')
@section('content')
<div class="min-h-screen" x-data="assessmentBank"><div class="mx-auto max-w-7xl space-y-6"><div class="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><h1 class="text-2xl font-bold text-gray-900">Bank Asesmen</h1><p class="mt-1 text-sm text-gray-500">Kelola template master komponen penilaian (CPMK/CPL) yang dapat digunakan di berbagai periode.</p></div><x-capstone::button href="/admin/assessment-bank/new" class="cursor-pointer gap-2 bg-indigo-600 hover:bg-indigo-700"><x-capstone::icon name="Plus" />Tambah Penilaian</x-capstone::button></div>

    <x-capstone::data-table title="Tabel Komponen" search-placeholder="Cari komponen..." :columns="[0=>'','code'=>'Kode','description'=>'Deskripsi','is_active'=>'Status','weight'=>'Bobot',1=>'Action']" empty-title="Tidak ada komponen ditemukan" empty-description="Coba ubah filter atau buat komponen pertama untuk memulai" icon="Search">
        <x-slot:bulkActions><div x-show="selected.length" x-cloak class="flex flex-wrap items-center justify-between gap-3 border-b bg-indigo-50 px-6 py-3"><span class="text-sm font-medium text-indigo-900" x-text="selected.length+' terpilih'"></span><div class="flex gap-2"><x-capstone::button variant="outline" size="sm" @click="mutate([...selected],'activate')" ::disabled="saving"><x-capstone::icon name="ArchiveRestore" />Aktifkan</x-capstone::button><x-capstone::button variant="outline" size="sm" @click="mutate([...selected],'deactivate')" ::disabled="saving"><x-capstone::icon name="Archive" />Nonaktifkan</x-capstone::button><x-capstone::button variant="destructive" size="sm" @click="confirmDelete()" ::disabled="saving"><x-capstone::icon name="Trash2" />Hapus</x-capstone::button></div></div></x-slot:bulkActions>
        <x-slot:selectionHeader><input type="checkbox" @change="selectPage($event.target.checked)" :checked="visible.length>0 && visible.every(t=>selected.includes(t.id))" :disabled="saving" aria-label="Pilih semua pada halaman ini" /></x-slot:selectionHeader>
        <x-slot:filters><select x-model="status" class="h-10 rounded-md border px-3 text-sm" aria-label="Status"><option value="all">Semua Status</option><option value="true">Aktif</option><option value="false">Nonaktif</option></select><x-capstone::button x-show="search || status!=='all'" variant="ghost" size="sm" class="h-10 text-gray-500" @click="search='';status='all'">Reset</x-capstone::button></x-slot:filters>
        <template x-for="item in visible" :key="item.id"><tr class="border-b hover:bg-muted/50"><td class="p-2"><input type="checkbox" x-model.number="selected" :value="item.id" :disabled="saving" :aria-label="'Pilih '+item.code" /></td><td class="p-2 font-medium" :class="!item.is_active && 'text-gray-500'" x-text="item.code"></td><td class="p-2 text-sm" :class="!item.is_active && 'text-gray-400'" x-text="item.description || '-'"></td><td class="p-2"><x-capstone::badge variant="outline" ::class="item.is_active ? 'border-green-600 text-green-800' : 'border-gray-600 text-gray-600'"><span class="mr-0.5 h-1.5 w-1.5 rounded-full" :class="item.is_active ? 'bg-green-600' : 'bg-gray-400'"></span><span x-text="item.is_active ? 'Aktif' : 'Nonaktif'"></span></x-capstone::badge></td><td class="p-2"><x-capstone::badge variant="outline" ::class="weightColor(Number(item.weight))" x-text="item.weight+'%'" /></td><td class="p-2"><div x-data="{menu:false}" @click.outside="menu=false" @keydown.escape="menu=false" class="relative"><x-capstone::button variant="ghost" size="icon-sm" @click="menu=!menu" ::disabled="saving" aria-label="Actions"><x-capstone::icon name="Ellipsis" /></x-capstone::button><div x-show="menu" x-cloak class="absolute right-0 z-20 min-w-36 rounded-md border bg-popover p-1 shadow-md"><a :href="url('/admin/assessment-bank/'+item.id+'/edit')" class="flex items-center gap-2 rounded-sm px-2 py-1.5 text-sm hover:bg-accent"><x-capstone::icon name="Edit" />Edit</a><button type="button" @click="menu=false;mutate([item.id],item.is_active ? 'deactivate' : 'activate')" class="flex w-full items-center gap-2 rounded-sm px-2 py-1.5 text-sm hover:bg-accent"><x-capstone::icon name="Archive" /><span x-text="item.is_active ? 'Nonaktifkan' : 'Aktifkan'"></span></button><button type="button" @click="menu=false;confirmDelete(item)" class="flex w-full items-center gap-2 rounded-sm px-2 py-1.5 text-sm text-red-600 hover:bg-accent"><x-capstone::icon name="Trash2" />Hapus</button></div></div></td></tr></template>
    </x-capstone::data-table>
    <x-capstone::dialog id="bank-delete" title="Hapus Komponen"><p class="py-4 text-sm text-muted-foreground" x-text="deleting ? 'Apakah Anda yakin ingin menghapus '+deleting.code+'?' : 'Apakah Anda yakin ingin menghapus '+deleteIds.length+' komponen?'"></p><div class="flex justify-end gap-2"><x-capstone::button variant="outline" @click="$el.closest('dialog').close()" ::disabled="saving">Batal</x-capstone::button><x-capstone::button variant="destructive" @click="mutate(deleteIds,'delete')" ::disabled="saving">Hapus</x-capstone::button></div></x-capstone::dialog>
</div></div>
@endsection
