@extends('capstone::layouts.app')
@section('title','Document Requirements')
@section('content')
<div class="space-y-6" x-data="documentRequirements">
    <div class="flex flex-wrap items-start justify-between gap-4"><h1 class="text-[32px] font-semibold text-grey-600 leading-tight">Document Requirements</h1><x-capstone::button variant="outline" size="sm" @click="$refs.defaults.showModal()" ::disabled="!editable"><x-capstone::icon name="Settings" class="mr-2 h-4 w-4" />Gunakan konfigurasi bawaan</x-capstone::button></div>
    @include('capstone::pages.admin.document-requirements.finalized')
    <x-capstone::data-table title="Phase Configuration" search-placeholder="Search..." :columns="[0=>'No','phase'=>'Fase',1=>'Syarat Dokumen',2=>'Tipe Dokumen',3=>'Action']" empty-title="No phases found" empty-description="Try adjusting your search.">
        <x-slot:filters><div class="flex items-center gap-2"><select x-model="selectedPeriod" @change="load()" :disabled="saving" class="h-9 w-48 rounded-md border px-3 text-sm" aria-label="Select period"><option value="" disabled>Select period</option><template x-for="period in periods" :key="period.id"><option :value="String(period.id)" x-text="period.name+(period.is_active ? ' (Active)' : '')"></option></template></select><div class="relative" x-data="{open:false}" @click.outside="open=false" @keydown.escape="open=false"><x-capstone::button variant="outline" size="sm" @click="open=!open" ::aria-expanded="open"><x-capstone::icon name="Filter" class="mr-2 h-4 w-4" />Filter</x-capstone::button><div x-show="open" x-cloak class="absolute right-0 z-20 mt-1 w-52 rounded-md border bg-popover p-1 text-popover-foreground shadow-md"><div class="px-3 py-2 text-xs font-semibold text-muted-foreground uppercase">Status</div>@foreach(['all'=>'All Phases','configured'=>'Configured','unconfigured'=>'Not Configured'] as $value=>$label)<button type="button" @click="status='{{ $value }}';page=1;open=false" class="w-full rounded-sm px-2 py-1.5 text-left text-sm hover:bg-accent">{{ $label }}</button>@endforeach</div></div></div></x-slot:filters>
        <template x-for="(item,index) in visible" :key="item.phase"><tr class="cursor-pointer border-b transition-colors hover:bg-muted/50" @click="window.location.href=phaseUrl(item.phase)"><td class="p-2" x-text="index+1"></td><td class="p-2"><x-capstone::badge variant="outline" ::class="colors[item.phase]" x-text="labels[item.phase]" /></td><td class="p-2"><span class="text-sm text-muted-foreground" x-text="item.document_count+' document'+(item.document_count!==1 ? 's' : '')"></span><span x-show="item.required_count" class="ml-1 text-xs text-emerald-600" x-text="'('+item.required_count+' required)'"></span></td><td class="p-2"><div class="flex flex-wrap gap-1"><template x-for="(name,key) in item.document_names" :key="key"><x-capstone::badge variant="secondary" class="text-xs" x-text="name" /></template></div><span x-show="!item.document_names.length" class="text-xs italic text-muted-foreground">Not configured</span></td><td class="p-2 text-right"><a :href="phaseUrl(item.phase)" @click.stop class="inline-flex h-8 w-8 items-center justify-center rounded-md hover:bg-accent" :aria-label="'Configure '+labels[item.phase]"><x-capstone::icon name="MoreHorizontal" class="h-4 w-4" /></a></td></tr></template>
    </x-capstone::data-table>
    <x-capstone::dialog id="defaults-confirm" x-ref="defaults" title="Gunakan konfigurasi bawaan"><p class="py-4 text-sm text-muted-foreground">Konfigurasi dokumen semua fase pada periode ini akan diganti dengan konfigurasi bawaan.</p><div class="flex justify-end gap-2"><x-capstone::button variant="outline" @click="$refs.defaults.close()" ::disabled="saving">Batal</x-capstone::button><x-capstone::button @click="save(true)" ::disabled="!editable" x-text="saving ? 'Saving...' : 'Gunakan konfigurasi bawaan'" /></div></x-capstone::dialog>
</div>
@endsection
