@extends('capstone::layouts.app')
@section('title','Document Types')
@section('content')
<div class="space-y-6" x-data="documentTypes">
    <div class="flex flex-wrap items-center justify-between gap-4"><div><h1 class="text-3xl font-bold tracking-tight">Document Types</h1><p class="text-muted-foreground">Manage dynamic document types (HKI, Hak Cipta, etc.).</p></div><x-capstone::button @click="edit()"><x-capstone::icon name="Plus" class="mr-2 h-4 w-4" />Add Type</x-capstone::button></div>
    <div class="relative max-w-sm"><x-capstone::icon name="Search" class="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" /><x-capstone::input x-model="search" placeholder="Search document types..." class="pl-9" aria-label="Search document types" /></div>
    <div :class="!loading && !error && filtered.length ? 'rounded-md border' : ''">
        <div x-show="loading" role="status" class="flex h-64 items-center justify-center"><x-capstone::icon name="Loader2" class="h-8 w-8 animate-spin" /><span class="sr-only">Loading</span></div><div x-show="error" x-cloak role="alert" class="rounded-lg border border-red-200 bg-red-50 p-4 text-sm text-red-700"><span x-text="error"></span><button type="button" @click="load()" class="ml-3 underline">Coba lagi</button></div>
        <div x-show="!loading && !error && !filtered.length" x-cloak class="flex flex-col items-center py-16 text-center"><x-capstone::icon name="Search" class="mb-4 h-8 w-8 text-muted-foreground" /><p class="font-medium" x-text="search ? 'No matching document types found' : 'No document types defined yet'"></p></div>
        <div x-show="!loading && !error && filtered.length" x-cloak class="overflow-x-auto"><table class="w-full text-sm"><thead><tr class="border-b">@foreach(['Name','Description','Phase','Status','Actions'] as $label)<th class="h-10 px-2 text-left font-medium {{ $loop->last ? 'text-right' : '' }}">{{ $label }}</th>@endforeach</tr></thead><tbody><template x-for="item in filtered" :key="item.id"><tr class="border-b transition-colors last:border-0 hover:bg-muted/50"><td class="p-2 font-medium" x-text="item.name"></td><td class="max-w-[300px] truncate p-2 text-muted-foreground" x-text="item.description || '-'"></td><td class="p-2"><x-capstone::badge variant="outline" x-text="item.phase || 'All'" /></td><td class="p-2"><x-capstone::badge variant="outline" class="border-transparent" ::class="item.is_active ? 'bg-primary text-primary-foreground' : 'bg-secondary text-secondary-foreground'" x-text="item.is_active ? 'Active' : 'Inactive'" /></td><td class="p-2 text-right whitespace-nowrap"><x-capstone::button variant="ghost" size="icon-sm" @click="edit(item)" aria-label="Edit document type"><x-capstone::icon name="Edit" /></x-capstone::button><x-capstone::button variant="ghost" size="icon-sm" class="text-destructive" @click="confirmDelete(item)" aria-label="Delete document type"><x-capstone::icon name="Trash2" /></x-capstone::button></td></tr></template></tbody></table></div>
    </div>
    <x-capstone::dialog id="type-form" width="sm:max-w-[500px]"><h2 class="text-lg font-semibold" x-text="editing ? 'Edit Document Type' : 'Add Document Type'"></h2><p class="mt-2 text-sm text-muted-foreground">Define a new document type category.</p><form @submit.prevent="save()"><div class="space-y-4 py-4"><x-capstone::field name="name" label="Name" placeholder="HKI" maxlength="255" required /><x-capstone::field name="description" label="Description" type="textarea" placeholder="Hak Kekayaan Intelektual" /><x-capstone::field name="phase" label="Phase (Optional)" type="select" :options="['ALL'=>'All Phases','PDC1'=>'PDC1','SEMPRO'=>'SEMPRO','PDC2'=>'PDC2','TA'=>'TA','EXPO'=>'EXPO','SIDANG'=>'SIDANG']" /></div><div class="flex justify-end"><x-capstone::button type="submit" ::disabled="saving" x-text="saving ? 'Saving...' : (editing ? 'Save Changes' : 'Create')" /></div></form></x-capstone::dialog>
    @include('capstone::partials.delete-dialog',['deleteTitle'=>'Delete Document Type','deleteDescription'=>'Delete this document type?'])
</div>
@endsection
