@extends('capstone::layouts.app')
@section('title','Groups')
@section('content')
<div x-data="adminGroups(false)" class="space-y-6"><div class="flex flex-wrap items-center justify-between gap-4"><h1 class="text-3xl font-bold tracking-tight">Groups</h1><div class="flex gap-2"></div></div>
@include('capstone::pages.admin.shared.toolbar')
@include('capstone::partials.loading')
<label class="text-sm">Status <select x-model="status" @change="page=1;load()" class="rounded border p-2"><option value="">Semua status</option><template x-for="s in ['FORMING','READY_FOR_BIDDING','TITLE_APPROVED','READY_FOR_FINALIZATION','KELOMPOK_FINAL','PDC1_ACTIVE','READY_FOR_SEMPRO','SEMPRO_DONE','PDC2_ACTIVE','EXPO_REGISTERED','READY_FOR_TA_INDIVIDUAL','CLOSED','DISSOLVED']"><option x-text="s"></option></template></select></label><div x-show="!loading && !error" x-cloak class="rounded-xl border bg-card overflow-hidden"><div class="overflow-x-auto"><table class="w-full text-left text-sm"><thead class="border-b bg-muted/40"><tr><th class="p-4">Kelompok</th><th class="p-4">Judul</th><th class="p-4">Periode</th><th class="p-4">Anggota</th><th class="p-4">Status</th><th class="p-4">Aksi</th></tr></thead><tbody><template x-for="item in items" :key="item.id"><tr class="border-b"><td class="p-4 " x-text="groupName(item)"></td><td class="p-4 " x-text="item.title?.title || item.name || '-'"></td><td class="p-4 " x-text="item.period?.name"></td><td class="p-4 " x-text="(item.members||[]).map(m=>person(m.student)).join(', ')"></td><td class="p-4 " x-text="item.status_label || item.status"></td><td class="p-4"><a :href="url('/admin/groups/'+item.id)" class="text-primary underline">Detail</a></td></tr></template></tbody></table></div><p x-show="!items.length" class="p-8 text-center">Tidak ada kelompok.</p><div class="flex items-center justify-between gap-3 p-4"><span x-text="(pagination.total||0)+' kelompok'"></span><div class="flex items-center gap-3"><select x-model.number="pageSize" @change="page=1;load()" class="rounded border p-1"><option>10</option><option>25</option><option>50</option></select><x-capstone::button variant="outline" size="sm" @click="page--;load()" ::disabled="loading || page<=1">Sebelumnya</x-capstone::button><span x-text="page+' / '+(pagination.last_page||1)"></span><x-capstone::button variant="outline" size="sm" @click="page++;load()" ::disabled="loading || page>=(pagination.last_page||1)">Berikutnya</x-capstone::button></div></div></div>
</div>
@endsection
