@extends('capstone::layouts.app')
@section('title','Locations')
@section('content')
<div class="min-h-screen" x-data="capstoneTable({endpoint:'/locations/all',writeEndpoint:'/locations',defaults:{name:'',type:'offline',capacity:null,description:'',is_active:true}})"><div class="mx-auto max-w-7xl space-y-6">
    <div class="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><h1 class="text-xl font-bold text-gray-900">Locations</h1><x-capstone::button @click="edit()" class="cursor-pointer gap-2"><x-capstone::icon name="Plus" />Tambah Lokasi</x-capstone::button></div>
    <x-capstone::data-table title="Location Table" search-placeholder="Cari lokasi..." :columns="['name'=>'Nama','type'=>'Tipe','capacity'=>'Kapasitas','is_active'=>'Status',0=>'Action']" empty-title="Tidak ada lokasi ditemukan" empty-description="Coba ubah filter atau buat lokasi baru" icon="MapPin">
        <x-slot:filters><select x-model="filters.type" @change="page=1" class="h-10 rounded-md border px-3 text-sm" aria-label="Tipe"><option value="all">Semua Tipe</option><option value="offline">Offline</option><option value="online">Online</option></select><select x-model="filters.is_active" @change="page=1" class="h-10 rounded-md border px-3 text-sm" aria-label="Status"><option value="all">Semua Status</option><option value="true">Aktif</option><option value="false">Nonaktif</option></select></x-slot:filters>
        <template x-for="item in visible" :key="item.id"><tr class="border-b transition-colors hover:bg-muted/50"><td class="p-2 align-middle"><div class="pl-2"><div class="flex items-center gap-2"><x-capstone::icon name="MapPin" class="h-4 w-4" ::class="item.is_active ? 'text-blue-600' : 'text-gray-400'" /><span class="font-medium" x-text="item.name"></span></div><p x-show="item.description" class="mt-0.5 ml-6 text-xs text-gray-500" x-text="item.description"></p></div></td><td class="p-2"><x-capstone::badge x-text="item.type==='offline' ? 'Offline' : 'Online'" /></td><td class="p-2 text-sm text-gray-600" x-text="item.capacity || '—'"></td><td class="p-2"><x-capstone::badge variant="outline" ::class="item.is_active ? 'border-green-600 text-green-800' : 'border-gray-600 text-gray-600'"><span class="mr-0.5 h-1.5 w-1.5 rounded-full" :class="item.is_active ? 'bg-green-600' : 'bg-gray-400'"></span><span x-text="item.is_active ? 'Aktif' : 'Nonaktif'"></span></x-capstone::badge></td><td class="p-2">@include('capstone::partials.row-actions')</td></tr></template>
    </x-capstone::data-table>
    <x-capstone::dialog id="record-form" class="sm:max-w-[500px]"><h2 class="text-lg font-semibold" x-text="editing ? 'Edit Location' : 'Add Location'"></h2><p class="mt-2 text-muted-foreground text-sm" x-text="editing ? 'Update the location details below.' : 'Create a new location for scheduling events and sessions.'"></p><form @submit.prevent="save"><div class="space-y-4 py-4"><x-capstone::field name="name" label="Name" placeholder="e.g., Lab IF-101, Zoom Meeting Room" required /><div class="grid grid-cols-2 gap-4"><x-capstone::field name="type" label="Type" type="select" :options="['offline'=>'Offline','online'=>'Online']" required /><x-capstone::field name="capacity" label="Capacity" type="number" min="1" /></div><x-capstone::field name="description" label="Description" type="textarea" /><x-capstone::field name="is_active" label="Active" type="checkbox" /></div><div class="flex justify-end gap-2"><x-capstone::button variant="outline" @click="$el.closest('dialog').close()">Cancel</x-capstone::button><x-capstone::button type="submit" ::disabled="saving" x-text="saving ? 'Saving...' : 'Save'" /></div></form></x-capstone::dialog>
    @include('capstone::partials.delete-dialog',['deleteTitle'=>'Hapus Lokasi','deleteDescription'=>'Lokasi harus dinonaktifkan sebelum dihapus. Apakah Anda yakin ingin menghapus'])
</div></div>
@endsection
