@extends('capstone::layouts.app')
@section('title','TA Defense Schedules')
@section('content')
<div x-data="capstoneAdminTaDefense" class="space-y-6">
    <div class="flex flex-wrap items-center justify-between gap-4"><div><h1 class="text-2xl font-semibold tracking-tight">TA Defense Schedules</h1><p class="text-muted-foreground text-sm mt-0.5">Manage individual TA defense schedules for students.</p></div><x-capstone::button @click="open()" ::disabled="!selectedPeriod || loading"><x-capstone::icon name="Plus" class="mr-2 h-4 w-4" />Schedule TA Defense</x-capstone::button></div>
    <div class="flex flex-col sm:flex-row gap-3"><label class="flex items-center gap-2"><span class="text-sm text-muted-foreground whitespace-nowrap">Period</span><select x-model="selectedPeriod" @change="page=1;load()" class="h-9 w-55 rounded-md border bg-transparent px-3 text-sm"><option value="all">All Periods</option><template x-for="period in periods" :key="period.id"><option :value="String(period.id)" x-text="period.name+(period.is_active?' (active)':'')"></option></template></select></label><label class="flex items-center gap-2"><span class="text-sm text-muted-foreground whitespace-nowrap">Status</span><select x-model="statusFilter" @change="page=1" class="h-9 w-40 rounded-md border bg-transparent px-3 text-sm"><option value="ALL">All Status</option><option value="SCHEDULED">Scheduled</option><option value="DONE">Done</option><option value="CANCELLED">Cancelled</option></select></label><div class="relative flex-1 sm:ml-auto sm:max-w-xs"><x-capstone::icon name="Search" class="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" /><x-capstone::input x-model="search" @input="page=1" class="pl-9" placeholder="Search student, NIM, group..." aria-label="Search schedules" /></div></div>
    @include('capstone::partials.loading')
    <div x-show="!loading && !error" x-cloak>
        <div x-show="!filtered.length" class="text-center py-16 text-muted-foreground border rounded-lg border-dashed"><x-capstone::icon name="GraduationCap" class="h-8 w-8 mx-auto mb-3 text-muted-foreground/40" /><p class="text-sm font-medium">No TA defense schedules found</p><p class="text-[13px] text-muted-foreground/60 mt-1" x-text="statusFilter!=='ALL'?'No '+statusFilter.toLowerCase()+' schedules. Try changing the status filter.':'Create a new schedule to get started.'"></p></div>
        <div x-show="filtered.length">@include('capstone::pages.admin.ta-defense.table')</div>
    </div>
    @include('capstone::pages.admin.ta-defense.form')
    <x-capstone::dialog id="admin-ta-cancel" title="Cancel Schedule" description="Are you sure you want to cancel this TA defense schedule? This action cannot be undone."><div class="py-4 text-sm space-y-1"><p x-text="students(cancelling || {})[0]?.name || ''"></p><p class="text-muted-foreground" x-text="date(cancelling?.date)"></p></div><div class="flex justify-end gap-2"><x-capstone::button variant="outline" @click="document.getElementById('admin-ta-cancel').close()">Keep Schedule</x-capstone::button><x-capstone::button variant="destructive" @click="cancel" ::disabled="saving">Cancel Schedule</x-capstone::button></div></x-capstone::dialog>
</div>
@endsection
