@extends('capstone::layouts.app')
@section('title','User Management')
@section('content')
<div x-data="adminUsers" class="space-y-6">
    <div class="flex flex-wrap items-center justify-between gap-4"><div><h1 class="text-3xl font-bold tracking-tight">User Management</h1><p class="mt-1 text-muted-foreground">Manage user accounts and access roles.</p></div><x-capstone::button href="/admin/users/new"><x-capstone::icon name="UserPlus" class="h-4 w-4" />Tambah User</x-capstone::button></div>
    <div class="flex flex-wrap gap-2 border-b pb-3" role="group" aria-label="Filter role">@foreach(['all'=>'Semua User','mahasiswa'=>'Mahasiswa','dosen'=>'Dosen','admin'=>'Admin'] as $key=>$label)<button type="button" @click="role='{{ $key }}';filter()" :aria-pressed="role==='{{ $key }}'" :class="role==='{{ $key }}'?'bg-primary text-primary-foreground':'hover:bg-muted text-muted-foreground'" class="rounded-md px-4 py-2 text-sm font-medium">{{ $label }}</button>@endforeach</div>
    <div class="flex flex-wrap items-center gap-3"><x-capstone::input type="search" x-model="search" @input.debounce.300ms="filter()" placeholder="Cari nama, email, NIM atau NIP..." aria-label="Cari users" class="min-w-48 flex-1" /><select x-model="status" @change="filter()" aria-label="Status akun" class="h-9 rounded-md border bg-background px-3 text-sm"><option value="all">Semua Status</option><option value="active">Aktif</option><option value="suspended">Ditangguhkan</option></select><x-capstone::button variant="destructive" x-show="selectedIds.length" @click="confirmDelete(items.filter(u=>selectedIds.includes(u.id)))" ::disabled="loading || saving"><span x-text="'Hapus '+selectedIds.length+' user'"></span></x-capstone::button></div>
    @include('capstone::partials.loading')
    <div x-show="!loading && !error" x-cloak class="space-y-4"><div class="overflow-x-auto rounded-xl border"><table class="w-full min-w-[820px] text-left text-sm"><thead class="border-b bg-muted/30"><tr><th class="w-12 p-4"><input type="checkbox" :checked="selectedAll" @change="toggleAll($event.target.checked)" aria-label="Pilih semua user pada halaman ini" class="accent-primary"></th><th class="p-4"><button type="button" @click="sort('name')">Nama <span x-show="sortKey==='name'" x-text="sortDirection==='asc'?'↑':'↓'"></span></button></th><th class="p-4">NIM / NIP</th><th class="p-4">Access Role</th><th class="p-4">Status</th><th class="p-4"><button type="button" @click="sort('created_at')">Tanggal Daftar <span x-show="sortKey==='created_at'" x-text="sortDirection==='asc'?'↑':'↓'"></span></button></th><th class="p-4 text-right">Action</th></tr></thead><tbody><template x-for="user in items" :key="user.id"><tr class="border-b last:border-0 hover:bg-muted/20">
        <td class="p-4"><input type="checkbox" :disabled="!user.can_delete" :checked="selectedIds.includes(user.id)" @change="toggleUser(user.id,$event.target.checked)" :aria-label="'Pilih '+user.name" class="accent-primary"></td><td class="p-4"><a :href="userUrl(user)" class="flex items-center gap-3"><span class="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-primary/10 font-semibold text-primary" x-text="initials(user)"></span><span><span class="block font-medium hover:underline" x-text="user.name"></span><span class="mt-1 block text-xs text-muted-foreground" x-text="user.email"></span></span></a></td><td class="p-4" x-text="[user.nim,user.nip].filter(Boolean).join(' / ')||'-'"></td><td class="p-4"><div class="flex flex-wrap gap-1"><template x-for="slug in user.roles" :key="slug"><span class="rounded-full border px-2 py-0.5 text-xs capitalize" :class="slug==='admin'?'bg-violet-50 text-violet-700':slug==='dosen'?'bg-blue-50 text-blue-700':'bg-green-50 text-green-700'" x-text="slug"></span></template></div></td><td class="p-4"><span class="rounded-full px-2 py-1 text-xs" :class="user.status==='active'?'bg-green-100 text-green-700':'bg-red-100 text-red-700'" x-text="user.status==='active'?'Aktif':'Ditangguhkan'"></span></td><td class="p-4 text-xs" x-text="date(user.created_at)"></td><td class="p-4"><div class="flex justify-end gap-2"><a :href="userUrl(user)" class="rounded border px-2 py-1 text-xs">Detail</a><a x-show="user.can_edit" :href="userUrl(user,true)" class="rounded border px-2 py-1 text-xs">Edit</a><button type="button" x-show="user.can_delete" @click="confirmDelete([user])" class="rounded border border-red-200 px-2 py-1 text-xs text-red-600">Hapus</button></div></td>
    </tr></template></tbody></table><p x-show="!items.length" class="p-12 text-center text-muted-foreground">Tidak ada user yang sesuai dengan filter.</p></div><div class="flex flex-wrap items-center justify-between gap-3 text-sm"><span class="text-muted-foreground" x-text="(pagination.total||0)+' user'"></span><div class="flex items-center gap-3"><select x-model.number="pageSize" @change="filter()" aria-label="Baris per halaman" class="rounded border bg-background p-1"><option>10</option><option>25</option><option>50</option><option>100</option></select><x-capstone::button variant="outline" size="sm" @click="page--;load()" ::disabled="page<=1 || loading">Sebelumnya</x-capstone::button><span x-text="page+' / '+pageCount"></span><x-capstone::button variant="outline" size="sm" @click="page++;load()" ::disabled="page>=pageCount || loading">Berikutnya</x-capstone::button></div></div></div>
    @include('capstone::pages.admin.users.delete-dialog')
</div>
@endsection
