@extends('capstone::layouts.app')
@section('title','Tugas Akhir (TA)')
@section('content')
<div x-data="capstoneTaSubmission" class="space-y-6 max-w-5xl mx-auto">
    @include('capstone::partials.loading')
    <div x-show="!loading && !error" x-cloak class="space-y-6">
        <div class="flex flex-col md:flex-row md:items-center justify-between gap-4"><div><h1 class="text-3xl font-bold tracking-tight">Tugas Akhir (TA)</h1><p class="text-muted-foreground" x-text="locked?'Individual thesis phase.':'Individual thesis submission and defense.'"></p></div><span x-show="!locked" class="inline-flex items-center rounded-md px-3 py-1 text-sm font-medium" :class="config.color">@foreach(['Lock','FileText','Clock','CheckCircle','Calendar','FileCheck'] as $icon)<x-capstone::icon :name="$icon" class="w-4 h-4 mr-1" x-show="config.icon==='{{ $icon }}'" />@endforeach<span x-text="config.label"></span></span></div>
        @include('capstone::pages.mahasiswa.ta-submission.locked')
        <template x-if="data && !locked"><div class="space-y-6">
            <x-capstone::card><div class="px-6 pb-3"><h2 class="text-lg font-semibold flex items-center gap-2"><x-capstone::icon name="User" class="w-5 h-5" />Student Information</h2></div><div class="px-6 flex flex-col md:flex-row gap-6"><div class="flex items-center gap-4"><span class="h-16 w-16 shrink-0 rounded-full flex items-center justify-center text-lg bg-primary/10 text-primary">{{ mb_substr($actor['name'] ?? 'Student',0,1) }}</span><div><p class="font-semibold text-lg">{{ $actor['name'] ?? 'Student' }}</p><p class="text-sm text-muted-foreground">Individual TA Phase</p></div></div><div class="hidden md:block h-16 w-px bg-border"></div><div class="flex-1 grid grid-cols-1 md:grid-cols-2 gap-4"><div><p class="text-sm text-muted-foreground">Group</p><p class="font-medium flex items-center gap-2"><x-capstone::icon name="Users" class="w-4 h-4" /><span x-text="'Group '+(data.group?.id || 'N/A')"></span></p></div><div class="min-w-0"><p class="text-sm text-muted-foreground">Title</p><p class="font-medium truncate" x-text="data.group?.title?.title || 'No title assigned'"></p></div>@foreach([1,2] as $number)<div><p class="text-sm text-muted-foreground">Supervisor {{ $number }}</p><p class="font-medium" x-text="data.group?.supervisor{{ $number }}?.name || 'Not assigned'"></p></div>@endforeach</div></div></x-capstone::card>
            <x-capstone::card title="Progress Overview" description="Track your TA submission progress"><div class="px-6"><div class="relative"><div class="hidden md:block absolute top-6 left-0 right-0 h-0.5 bg-muted"></div><div class="grid grid-cols-1 md:grid-cols-5 gap-4 md:gap-2">
                @foreach([['Upload Documents','Submit all required documents'],['Document Review','Supervisor review in progress'],['Documents Approved','Ready for scheduling'],['Sidang Scheduled','Defense date confirmed'],['Defense Complete','TA defense finished']] as $index=>$step)
                <div class="relative flex md:flex-col items-start md:items-center gap-3 md:gap-2"><div class="relative z-10 flex h-12 w-12 shrink-0 items-center justify-center rounded-full border-2 transition-all duration-300" :class="{{ $index }}<currentStep?'bg-primary border-primary text-primary-foreground':{{ $index }}===currentStep?'bg-primary border-primary text-primary-foreground ring-4 ring-primary/20':'bg-background border-muted text-muted-foreground'"><x-capstone::icon name="CheckCircle" class="h-5 w-5" x-show="{{ $index }}<currentStep" /><span class="text-sm font-semibold" x-show="{{ $index }}>=currentStep">{{ $index+1 }}</span></div><div class="flex-1 md:text-center"><p class="text-sm font-medium" :class="{{ $index }}===currentStep?'text-primary':{{ $index }}<currentStep?'text-foreground':'text-muted-foreground'">{{ $step[0] }}</p><p class="text-xs text-muted-foreground hidden md:block">{{ $step[1] }}</p></div>@if($index<4)<div class="md:hidden absolute left-6 top-12 w-0.5 h-full" :class="{{ $index }}<currentStep?'bg-primary':'bg-muted'"></div>@endif</div>
                @endforeach
            </div></div></div></x-capstone::card>
            <div role="status" class="rounded-lg border p-4 flex gap-3" :class="config.color">@foreach(['FileText','Clock','CheckCircle','Calendar','FileCheck','Lock'] as $icon)<x-capstone::icon :name="$icon" class="h-4 w-4 shrink-0 mt-0.5" x-show="config.icon==='{{ $icon }}'" />@endforeach<div><h2 class="font-semibold" x-text="config.label"></h2><p class="text-sm" x-text="config.description"></p></div></div>
            @include('capstone::pages.mahasiswa.ta-submission.documents')
            <x-capstone::card x-show="currentStatus==='TA_DOCUMENTS_APPROVED'" class="bg-green-50 border-green-200"><h2 class="px-6 text-lg font-semibold flex items-center gap-2 text-green-800"><x-capstone::icon name="CheckCircle" class="w-5 h-5" />Documents Approved!</h2><p class="px-6 text-green-700">All your TA documents have been approved. You are now waiting for the administrator to schedule your sidang TA.</p></x-capstone::card>
            @include('capstone::pages.mahasiswa.ta-submission.defense')
            <x-capstone::card class="bg-muted/50"><h2 class="px-6 text-base font-semibold flex items-center gap-2"><x-capstone::icon name="Info" class="w-4 h-4" />Important Information</h2><ul class="px-6 space-y-2 text-sm text-muted-foreground">@foreach(['Upload all required documents to proceed to sidang TA.','Documents must be approved by your supervisors before scheduling.','Contact your supervisor for guidance during the TA phase.'] as $info)<li class="flex items-start gap-2"><x-capstone::icon name="CheckCircle" class="h-4 w-4 shrink-0 mt-0.5 text-primary" /><span>{{ $info }}</span></li>@endforeach</ul></x-capstone::card>
        </div></template>
    </div>
    <x-capstone::dialog id="ta-upload" title="Upload Document" width="sm:max-w-[500px]"><p class="text-sm text-muted-foreground" x-text="'Upload '+selectedType+' for TA submission'"></p><form @submit.prevent="submit"><div class="grid gap-4 py-4"><div class="grid gap-2"><label for="ta-file" class="text-sm font-medium">Document File</label><x-capstone::input id="ta-file" type="file" accept=".pdf,.doc,.docx" @change="selectFile($event.target.files[0])" ::disabled="uploading" /><p class="text-xs text-muted-foreground">Accepted formats: PDF, DOC, DOCX. Max size: 10MB</p></div><div x-show="file" class="p-3 bg-muted rounded-lg"><p class="text-sm font-medium">Selected file:</p><p class="text-sm text-muted-foreground" x-text="file?.name"></p><p class="text-xs text-muted-foreground" x-text="((file?.size || 0)/1024/1024).toFixed(2)+' MB'"></p></div><div x-show="uploading" class="space-y-2"><div class="flex justify-between text-sm"><span>Uploading...</span><span x-text="progress+'%'"></span></div><div role="progressbar" aria-valuemin="0" aria-valuemax="100" :aria-valuenow="progress" class="h-2 bg-primary/20 rounded-full overflow-hidden"><div class="h-full bg-primary transition-all" :style="{width:progress+'%'}"></div></div></div></div><div class="flex justify-end gap-2"><x-capstone::button variant="outline" ::disabled="uploading" @click="document.getElementById('ta-upload').close()">Cancel</x-capstone::button><x-capstone::button type="submit" ::disabled="!file || uploading"><x-capstone::icon name="Upload" class="mr-2 h-4 w-4" x-show="!uploading" /><x-capstone::icon name="Loader2" class="mr-2 h-4 w-4 animate-spin" x-show="uploading" /><span x-text="uploading?'Uploading...':'Upload Document'"></span></x-capstone::button></div></form></x-capstone::dialog>
</div>
@endsection
