<div x-show="locked">
    <template x-if="readiness"><div role="alert" class="rounded-lg border border-amber-500 bg-amber-50 p-4 flex items-start gap-3"><x-capstone::icon name="AlertTriangle" class="h-4 w-4 text-amber-600 shrink-0 mt-0.5" /><div class="text-sm text-amber-700"><h2 class="font-medium text-amber-800 mb-1">🔒 Belum Ready for TA Individual</h2><p x-show="!readiness.expo_completed" class="mb-2">Complete EXPO with your group.</p><div x-show="!readiness.expo_documents.completed" class="mb-2"><p class="font-medium">Dokumen EXPO belum lengkap/disetujui:</p><ul class="mt-1 list-disc pl-5 space-y-1"><template x-for="type in readiness.expo_documents.pending_types" :key="type"><li x-text="type"></li></template></ul></div>
        @foreach(['nilai_dosen'=>['NILAI_DOSEN','Menunggu NILAI_DOSEN dosen pembimbing:'],'milestone'=>['MILESTONE','Menunggu penilaian MILESTONE dosen pembimbing:'],'expo_evaluation'=>['evaluasi EXPO','Menunggu evaluasi EXPO dari dosen pembimbing:']] as $key=>[$label,$message])
        <p x-show="!readiness.{{ $key }}.configured" class="mb-2">Komponen {{ $label }} belum dikonfigurasi admin untuk periode ini.</p><div x-show="readiness.{{ $key }}.configured && !readiness.{{ $key }}.completed" class="mb-2"><p class="font-medium">{{ $message }}</p><ul class="mt-1 space-y-1"><template x-for="supervisor in readiness.{{ $key }}.supervisors.filter(s=>s.status==='pending')" :key="supervisor.id"><li><span x-text="supervisor.name+' ('+roleLabel(supervisor.role)+')'"></span><span class="text-sm text-muted-foreground ml-2" x-text="'- '+supervisor.submitted_components+'/'+supervisor.total_components+' komponen'"></span></li></template></ul></div>
        @endforeach
        <p x-show="!readiness.peer_review.configured" class="mb-2">Indikator peer review belum diset oleh admin pada Period Setup.</p><div x-show="readiness.peer_review.configured && !readiness.peer_review.completed"><p class="font-medium">Peer review belum lengkap:</p><p class="text-sm text-muted-foreground mt-1" x-text="'Progress: '+readiness.peer_review.completed_members+'/'+readiness.peer_review.total_members+' mahasiswa selesai.'"></p><ul class="mt-1 space-y-1"><template x-for="student in readiness.peer_review.incomplete_students" :key="student.student_id"><li x-text="student.student_name+' ('+student.student_nim+')'"></li></template></ul></div>
    </div></div></template>
    <x-capstone::card x-show="!readiness" class="border-red-200 bg-red-50"><div class="px-6"><h2 class="font-semibold text-red-800 flex items-center gap-2"><x-capstone::icon name="Lock" class="h-5 w-5 text-red-600" />TA Phase Locked</h2><p class="text-sm text-red-700 mt-2">TA phase is currently locked.</p></div><div class="px-6"><p class="text-sm text-red-700 mb-4">To unlock TA phase, you need to:</p><ol class="space-y-3">@foreach(['Complete EXPO with your group','Submit peer review for all group members'] as $i=>$message)<li class="flex items-start gap-3"><span class="flex items-center justify-center w-6 h-6 rounded-full bg-red-200 text-red-700 text-xs font-semibold">{{ $i+1 }}</span><span class="text-sm text-red-700">{{ $message }}</span></li>@endforeach</ol></div></x-capstone::card>
</div>
