@extends('capstone::layouts.app')
@section('title','Detail Expo')
@section('content')
<div x-data="capstoneExpoDetail" class="container py-6 space-y-6 animate-in fade-in duration-500">
    <div class="flex items-center gap-4"><x-capstone::button href="/mahasiswa/expo" variant="outline" size="icon" class="rounded-full" aria-label="Kembali ke Expo"><x-capstone::icon name="ArrowLeft" class="h-4 w-4" /></x-capstone::button><div><h1 class="text-3xl font-extrabold tracking-tight" x-text="data?.expo_event.name || 'Expo'"></h1><p class="text-muted-foreground">Detail expo dan self-evaluation</p></div></div>
    @include('capstone::partials.loading')
    <template x-if="data && !loading && !error"><div class="space-y-6">
        <x-capstone::card class="border-primary/20 shadow-md"><div class="p-6 grid grid-cols-1 md:grid-cols-3 gap-6"><div class="space-y-2"><div class="flex items-center gap-2 text-sm text-muted-foreground"><x-capstone::icon name="Calendar" class="h-4 w-4" /><span x-text="date(data.expo_event.date)"></span></div><div class="flex items-center gap-2 text-sm text-muted-foreground"><x-capstone::icon name="Clock" class="h-4 w-4" /><span x-text="data.expo_event.start_time.slice(0,5)+' – '+data.expo_event.end_time.slice(0,5)"></span></div><div class="flex items-center gap-2 text-sm text-muted-foreground"><x-capstone::icon name="MapPin" class="h-4 w-4" /><span x-text="data.expo_event.room || 'TBA'"></span></div></div><div class="space-y-3"><p class="text-sm font-semibold">Progress Anda</p>@foreach(['Self-Evaluation'=>'evaluationDone','Upload Dokumen'=>'!!data.my_document'] as $label=>$condition)<div class="space-y-2"><div class="flex items-center justify-between text-xs"><span>{{ $label }}</span><span :class="{{ $condition }} ? 'text-green-600 font-semibold' : 'text-orange-600'" x-text="{{ $condition }} ? 'Selesai' : 'Belum'"></span></div><div class="bg-primary/20 h-2 rounded-full overflow-hidden"><div class="h-full bg-primary" :style="{width:{{ $condition }} ? '100%' : '0%'}"></div></div></div>@endforeach</div><div class="space-y-2"><p class="text-sm font-semibold">Kelompok</p><p class="text-sm text-muted-foreground" x-text="data.group.code"></p><p class="text-2xl font-black text-primary" x-text="weighted"></p><p class="text-xs text-muted-foreground">Nilai Akhir (Weighted)</p></div></div></x-capstone::card>
        <div class="grid grid-cols-1 lg:grid-cols-12 gap-6">
            <div class="lg:col-span-4 space-y-6"><x-capstone::card><h2 class="px-6 font-semibold flex items-center gap-2"><x-capstone::icon name="User" class="h-5 w-5 text-primary" />Anggota Kelompok</h2><div class="px-6 space-y-3"><template x-for="member in data.members" :key="member.id"><div class="flex items-center gap-3 bg-muted/30 p-3 rounded-lg border"><span class="h-9 w-9 rounded-full bg-primary/10 flex items-center justify-center text-primary font-bold text-xs shrink-0" x-text="member.name.charAt(0)"></span><div class="flex-1 min-w-0"><p class="text-sm font-semibold truncate" x-text="member.name"></p><p class="text-xs text-muted-foreground" x-text="member.nim"></p></div><div class="flex gap-1 shrink-0"><x-capstone::badge variant="secondary" x-show="member.has_submitted_evaluation" class="text-xs bg-green-100 text-green-700"><x-capstone::icon name="CheckCircle2" class="h-3 w-3" />Eval</x-capstone::badge><x-capstone::badge variant="secondary" x-show="member.has_uploaded_document" class="text-xs bg-blue-100 text-blue-700"><x-capstone::icon name="FileText" class="h-3 w-3" />Doc</x-capstone::badge></div></div></template></div></x-capstone::card>
                <x-capstone::card><div class="px-6"><h2 class="font-semibold flex items-center gap-2"><x-capstone::icon name="FileText" class="h-5 w-5 text-primary" />Dokumen EXPO</h2><p class="text-sm text-muted-foreground">Upload dokumen pendukung EXPO Anda</p></div><div class="px-6 space-y-4"><div x-show="data.my_document" class="p-4 bg-green-50 rounded-lg border border-green-200 flex items-center gap-3"><x-capstone::icon name="CheckCircle2" class="h-5 w-5 text-green-600 shrink-0" /><div class="min-w-0"><p class="text-sm font-medium truncate" x-text="data.my_document?.original_name"></p><p class="text-xs text-green-600" x-text="'Status: '+data.my_document?.status"></p></div></div><div x-show="!data.my_document" class="space-y-3"><button type="button" @click="document.getElementById('expo-file').click()" @dragover.prevent @drop.prevent="upload($event.dataTransfer.files[0])" :disabled="uploading" class="w-full p-4 border-2 border-dashed rounded-lg text-center hover:border-primary/50 transition-colors"><x-capstone::icon name="Upload" class="h-8 w-8 mx-auto mb-2 text-muted-foreground" /><span class="block text-sm text-muted-foreground">Drag &amp; drop atau klik untuk upload</span><span class="block text-xs text-muted-foreground mt-1">PDF, DOC, DOCX, PPT, PPTX (maks. 10MB)</span></button><input id="expo-file" type="file" class="hidden" accept=".pdf,.doc,.docx,.ppt,.pptx" @change="upload($event.target.files[0])"><x-capstone::button variant="outline" class="w-full" ::disabled="uploading" @click="document.getElementById('expo-file').click()"><x-capstone::icon name="Upload" /><span x-text="uploading ? 'Uploading...' : 'Pilih File'"></span></x-capstone::button></div></div></x-capstone::card>
            </div>
            <div class="lg:col-span-8 space-y-6 min-w-0"><x-capstone::card class="shadow-xl"><div class="px-6"><h2 class="font-semibold">Self-Evaluation EXPO</h2><p class="text-sm text-muted-foreground" x-text="submitted ? 'Self-evaluation sudah dikirim (read-only)' : 'Isi penilaian untuk setiap komponen EXPO'"></p></div><p x-show="!data.components.length" class="px-6 text-sm text-muted-foreground">Komponen penilaian belum dikonfigurasi.</p><div class="divide-y divide-border"><template x-for="comp in data.components" :key="comp.id"><fieldset :disabled="submitted || saving" class="p-6 space-y-4 hover:bg-muted/5 transition-colors"><div class="flex items-start justify-between gap-4"><div class="space-y-1"><div class="flex items-center gap-2"><span class="text-xs font-bold px-2 py-0.5 bg-primary/10 text-primary rounded" x-text="comp.code"></span><h3 class="font-bold text-lg" x-text="comp.name"></h3></div><p class="text-sm text-muted-foreground" x-text="comp.description"></p></div><div class="shrink-0 text-right"><p class="text-xs font-bold text-muted-foreground uppercase">Bobot</p><p class="text-lg font-extrabold text-primary" x-text="comp.weight+'%'"></p></div></div><div class="space-y-2"><div class="text-xs flex justify-between"><label :for="'expo-score-'+comp.id">Nilai Anda</label><span class="font-bold text-primary" x-text="'Nilai: '+(scores[comp.id] || 0)"></span></div><div class="flex gap-4 items-start"><div class="w-1/3"><x-capstone::input ::id="'expo-score-'+comp.id" type="number" min="1" max="100" step="0.01" class="text-center font-bold" placeholder="0-100" x-model.number="scores[comp.id]" ::readonly="submitted" /></div><textarea x-model="notes[comp.id]" :readonly="submitted" maxlength="5000" :aria-label="'Catatan '+comp.name" placeholder="Catatan/feedback (opsional)..." class="flex-1 min-w-0 w-full h-10 min-h-[40px] rounded-md border px-3 text-sm py-2"></textarea></div></div></fieldset></template></div></x-capstone::card>
                <x-capstone::card class="border-primary shadow-lg bg-primary/5"><div class="p-6 flex flex-col md:flex-row items-center justify-between gap-6"><div class="space-y-2"><h4 class="font-bold text-muted-foreground">Ringkasan Nilai</h4><div class="text-center"><p class="text-xs text-muted-foreground">Weighted Score</p><p class="text-3xl font-black text-primary" x-text="weighted"></p></div></div><div class="flex gap-4"><x-capstone::button href="/mahasiswa/expo" variant="outline">Kembali</x-capstone::button><x-capstone::button size="lg" class="px-8 font-bold shadow-xl shadow-primary/20 hover:scale-105 transition-transform" x-show="!submitted" ::disabled="saving || !data.components.length" @click="submit"><x-capstone::icon name="Save" /><span x-text="saving ? 'Menyimpan...' : 'Simpan Self-Evaluation'"></span></x-capstone::button><x-capstone::badge variant="secondary" x-show="submitted" class="bg-green-100 text-green-700"><x-capstone::icon name="CheckCircle2" />Submitted</x-capstone::badge></div></div></x-capstone::card>
            </div>
        </div>
    </div></template>
</div>
@endsection
