@extends('capstone::layouts.app')
@section('title','Registration')
@section('content')
<div x-data="capstoneRegistration">
@include('capstone::partials.loading')
<div x-show="!loading && registered" x-cloak class="max-w-2xl mx-auto py-12"><x-capstone::card class="border-green-200 bg-green-50/50"><div class="px-6 pt-6 pb-6 text-center"><x-capstone::icon name="CheckCircle" class="h-16 w-16 text-green-600 mx-auto mb-4" /><h2 class="text-2xl font-bold text-green-800 mb-2">Registration Complete!</h2><p class="text-green-700 mb-4">You are registered for: <strong x-text="registered?.name || 'Selected Period'"></strong></p><p class="text-sm text-green-600 mb-6">Redirecting to dashboard...</p><x-capstone::button href="/mahasiswa/dashboard">Go to Dashboard<x-capstone::icon name="ArrowRight" class="ml-2 h-4 w-4" /></x-capstone::button></div></x-capstone::card></div>
<div x-show="!loading && isPending" x-cloak class="max-w-2xl mx-auto py-12"><x-capstone::card class="border-amber-200 bg-amber-50/50"><div class="px-6 pt-6 pb-6 text-center"><x-capstone::icon name="Clock" class="h-16 w-16 text-amber-600 mx-auto mb-4" /><h2 class="text-2xl font-bold text-amber-800 mb-2">Join Request Pending</h2><p class="text-amber-700 mb-2">Your request to join <strong x-text="requestedPeriodName"></strong> is waiting for admin approval.</p><p class="text-sm text-amber-600 mb-6">You will be notified once an admin reviews your request. Group, title, and other features unlock after approval.</p><x-capstone::button class="border-amber-300 text-amber-800" @click="cancelRequest()" ::disabled="cancelling"><span x-text="cancelling ? 'Cancelling...' : 'Cancel Request'"></span></x-capstone::button></div></x-capstone::card></div>
<div x-show="!loading && !error && !registered && !isPending" x-cloak class="max-w-4xl mx-auto py-8 px-4"><div class="text-center mb-8"><div class="inline-flex items-center justify-center w-16 h-16 rounded-full bg-primary/10 mb-4"><x-capstone::icon name="GraduationCap" class="h-8 w-8 text-primary" /></div><h1 class="text-3xl font-bold tracking-tight mb-2">Welcome, {{ $actor['name'] ?? 'Student' }}!</h1><p class="text-muted-foreground text-lg max-w-2xl mx-auto">To get started, request to join an academic period below. An admin will review your request.</p></div>
<div x-show="isRejected" class="mb-8 relative w-full rounded-lg border border-red-200 bg-red-50/50 px-4 py-3 text-sm grid grid-cols-[auto_1fr] gap-x-3"><x-capstone::icon name="CircleAlert" class="text-red-600" /><div><h2 class="font-medium text-red-800">Previous Request Rejected</h2><p class="text-red-700">Reason: <span x-text="myRequest?.rejection_reason || 'No reason provided'"></span></p><p class="text-muted-foreground mt-1">You can send a new join request below.</p></div></div>
<div role="note" class="mb-8 relative w-full rounded-lg border px-4 py-3 text-sm grid grid-cols-[auto_1fr] gap-x-3"><x-capstone::icon name="Calendar" /><div><h2 class="font-medium">Approval Required</h2><p class="text-muted-foreground">You can only have one join request at a time. Creating or joining a group, browsing titles, and other features unlock after an admin approves your request.</p></div></div>
<x-capstone::card class="border-dashed" x-show="!periods.length"><div class="px-6 pt-8 pb-8 text-center"><x-capstone::icon name="Calendar" class="h-12 w-12 text-muted-foreground mx-auto mb-4" /><h3 class="text-lg font-medium mb-2">No Active Periods</h3><p class="text-muted-foreground">There are no active periods available for registration at this time. Please check back later or contact your administrator.</p></div></x-capstone::card>
<div class="grid gap-4 md:grid-cols-2"><template x-for="period in periods" :key="period.id"><x-capstone::card class="relative overflow-hidden"><div class="px-6"><div class="flex items-start justify-between"><div><h2 class="text-xl font-semibold" x-text="period.name"></h2><div class="mt-1.5 text-sm text-muted-foreground flex items-center gap-2"><x-capstone::icon name="Calendar" class="h-3.5 w-3.5" /><span x-text="date(period.start_date)+' - '+date(period.end_date)"></span></div></div><x-capstone::badge class="bg-green-600">Open</x-capstone::badge></div></div><div class="px-6"><x-capstone::button class="w-full" size="lg" @click="register(period)" ::disabled="saving!==null"><span x-text="saving===period.id ? 'Sending request...' : 'Request to Join'"></span><x-capstone::icon name="ArrowRight" class="ml-2 h-4 w-4" /></x-capstone::button></div></x-capstone::card></template></div><p class="text-center text-sm text-muted-foreground mt-8">Need help? Contact your academic advisor or administrator for assistance with period registration.</p>
</div></div>
@endsection
