@props(['title'=>null,'searchPlaceholder'=>'Cari...','columns'=>[],'emptyTitle'=>'Tidak ada data ditemukan','emptyDescription'=>'Coba ubah filter','icon'=>'FileText','grouped'=>false])
<div class="rounded-xl border">
    <div class="border-b px-6 py-4"><div class="flex flex-col gap-4 sm:flex-row">@if($title)<h2 class="text-lg font-semibold text-gray-900 flex items-center">{{ $title }}</h2>@endif<div class="flex flex-1 flex-col gap-3 sm:flex-row sm:justify-end"><div class="relative w-full sm:w-72"><x-capstone::icon name="Search" class="absolute top-1/2 left-3 h-4 w-4 -translate-y-1/2 text-gray-400" /><x-capstone::input :placeholder="$searchPlaceholder" x-model.debounce.200ms="search" @input="page=1" class="h-10 pl-9" aria-label="{{ $searchPlaceholder }}" /></div>{{ $filters ?? '' }}</div></div></div>
    {{ $bulkActions ?? '' }}
    @include('capstone::partials.loading')
    <div x-show="!loading && !error && !filtered.length" x-cloak class="flex flex-col items-center justify-center py-16 px-4 text-center"><div class="mb-4 rounded-full bg-gray-100 p-4"><x-capstone::icon :name="$icon" class="h-8 w-8 text-gray-400" /></div><p class="font-medium text-gray-500">{{ $emptyTitle }}</p><p class="mt-1 text-sm text-gray-400">{{ $emptyDescription }}</p></div>
    <div x-show="!loading && !error && filtered.length" x-cloak class="relative w-full overflow-x-auto"><table class="w-full caption-bottom text-sm"><thead class="[&_tr]:border-b"><tr class="bg-gray-50/50 border-b">@foreach($columns as $key=>$label)<th class="h-10 px-2 text-left align-middle font-semibold text-gray-700 whitespace-nowrap">@if($loop->first && isset($selectionHeader)){{ $selectionHeader }}@elseif(is_string($key))<button type="button" @click="sort('{{ $key }}')" class="inline-flex items-center gap-2 py-1.5">{{ $label }}<x-capstone::icon name="ArrowUpDown" class="h-4 w-4" /></button>@else{{ $label }}@endif</th>@endforeach</tr></thead>@if($grouped){{ $slot }}@else<tbody class="[&_tr:last-child]:border-0">{{ $slot }}</tbody>@endif</table></div>
    <div x-show="!loading && !error && filtered.length" x-cloak class="flex flex-wrap items-center justify-between gap-4 border-t px-6 py-4 text-sm"><p class="text-muted-foreground"><span x-text="filtered.length"></span> data</p><div class="flex flex-wrap items-center gap-4"><label class="flex items-center gap-2">Rows per page<select x-model.number="pageSize" @change="page=1" class="rounded-md border h-8 px-2"><option>10</option><option>25</option><option>50</option><option>100</option></select></label><span>Page <span x-text="Math.min(page,pageCount)"></span> of <span x-text="pageCount"></span></span><div class="flex gap-2"><x-capstone::button variant="outline" size="sm" @click="page=1" ::disabled="page<=1" aria-label="First page">«</x-capstone::button><x-capstone::button variant="outline" size="sm" @click="page=Math.max(1,page-1)" ::disabled="page<=1" aria-label="Previous page">‹</x-capstone::button><x-capstone::button variant="outline" size="sm" @click="page=Math.min(pageCount,page+1)" ::disabled="page>=pageCount" aria-label="Next page">›</x-capstone::button><x-capstone::button variant="outline" size="sm" @click="page=pageCount" ::disabled="page>=pageCount" aria-label="Last page">»</x-capstone::button></div></div></div>
</div>
