@extends('capstone::layouts.app')
@section('title','Detail Kelompok')
@section('content')
<div x-data="adminGroups(true)" class="space-y-6"><div class="flex flex-wrap items-center justify-between gap-4"><h1 class="text-3xl font-bold tracking-tight">Detail Kelompok</h1><div class="flex gap-2"><x-capstone::button href="/admin/groups" variant="outline">Kembali</x-capstone::button></div></div>
@include('capstone::pages.admin.shared.toolbar')
@include('capstone::partials.loading')
<div x-show="!loading && !error && group" x-cloak class="space-y-6"><x-capstone::card><div class="space-y-4 px-6"><h2 class="text-xl font-semibold" x-text="group?.title?.title || groupName(group)"></h2><div class="flex flex-wrap gap-4 text-sm"><span x-text="group?.period?.name"></span><span class="rounded-full border px-3" x-text="group?.status"></span></div><div class="grid gap-4 md:grid-cols-2"><div><h3 class="font-medium">Anggota</h3><template x-for="member in group?.members || []" :key="member.id"><p class="mt-2 text-sm" x-text="person(member.student)+(member.is_leader?' (Ketua)':'')+' - '+(member.student?.student_number||'')"></p></template></div><div><h3 class="font-medium">Pembimbing</h3><p x-text="person(group?.supervisor1)"></p><p x-text="person(group?.supervisor2)"></p><form @submit.prevent="assign()" class="mt-3 flex gap-2"><select x-model="supervisorId" required class="min-w-0 rounded border p-2"><option value="">Pembimbing 2...</option><template x-for="lecturer in lecturers" :key="lecturer.id"><option :value="lecturer.lecturer_id || lecturer.lecturer?.id || lecturer.id" x-text="person(lecturer)"></option></template></select><x-capstone::button type="submit" ::disabled="saving || !supervisorId">Simpan</x-capstone::button></form></div></div></div></x-capstone::card><x-capstone::card title="Dokumen"><div class="px-6"><template x-for="doc in group?.documents || []" :key="doc.id"><div class="flex justify-between gap-3 border-b py-3 text-sm"><span x-text="doc.phase+' / '+doc.document_type"></span><span x-text="doc.status"></span></div></template><p x-show="!group?.documents?.length" class="text-muted-foreground">Belum ada dokumen.</p><a :href="url('/admin/document-uploads')+'?group_id='+group?.id" class="mt-4 inline-block text-primary underline">Lihat unggahan</a></div></x-capstone::card><x-capstone::card title="Jadwal"><div class="px-6"><template x-for="schedule in group?.schedules || []" :key="schedule.id"><p class="border-b py-3 text-sm" x-text="schedule.type+' - '+date(schedule.date)+' - '+(schedule.room||'-')"></p></template><p x-show="!group?.schedules?.length">Belum ada jadwal.</p></div></x-capstone::card></div>
</div>
@endsection
